### ISSUE TITLE
adjust initial location of popup for this environment

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#103]
we should adjust the initial location of the popup in the alpheios reader environment so that it's below the navigation bars.

Dependent upon alpheios-project/embed-lib#40

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
this is up for testing on the texts-test site. (It's in embed-lib 1.0.0.6)

**Comment by monzug** [comment]
from overlay, I clicked on Info, Browse Inflection Tables, Options and they all opened in the top left corner above the navigation bar. as per morphology pop-up, this opens below the navigation bar. tested in Chrome after resetting all the options and restarting the browser to avoid conflict with movable pop-up.

**Comment by balmas** [comment]
yes it's morphology popup only.
