### ISSUE TITLE
Scrolling text keep repeating the next passage

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#106]
while verifying that issue #66 is not longer reproducible, I noticed that when scrolling down, the next passage is added to the current view but it's repeated several times.
to repro:
go to http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0893.phi003.perseus-lat2/passage/5.31-5.60
scroll down the page and notice that it will show also the next passage 5.60 to 5.90. 
at this point the section is 5.31-5.90 (between the arrows). and the lines at the bottom go from 65 to 94, then again 65 to 94 for several repetition.
I think we have seen this issue before.
see screenshot
![text-repeated](https://user-images.githubusercontent.com/41396793/56809932-02a3f180-6803-11e9-840e-7b10a6471d06.JPG)

**Comment by monzug** [comment]
reproducible on mobile too

**Comment by monzug** [comment]
still reproducible in latest build 1.0.0.6

**Comment by irina060981** [comment]
I think it is fixed too here - https://github.com/alpheios-project/alpheios_nemo_ui/pull/115
Merged and closed
