### ISSUE TITLE
Quotes in Cicero are not displayed 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#11]
In Cicero, Academica we don't display the quotes, instead we use a font that is way too big.
e.g. in Perseus, we have “Omitte ista quae nec percunctari nec audire sine molestia possumus quaeso” with quotes as it's a conversation. in Scaife and Alpheios we do not display the quotes. 
the xml source is <quote>Omitte ista quae nec percunctari nec audire sine molestia possumus quaeso</quote>
in this book urn:cts:latinLit:phi0474.phi045, quotes are widely used. I did only find the tags <quote> </quotes> and <quote rend="blockquote"></quotes>
Bridget said:
the quotes at the top are quotes wrapped inside other quotes, where one 
quote tag probably means put "" around it and the other means set it off 
as a block quote because it's a citation. Sometimes this distinction is 
marked with the rend attribute, as it is in this case, there is an outer 
<quote rend="blockquote"> tag and inside it a <quote> without the rend 
attribute that probably is meant to be rendered in "". I don't know how 
consistent or inconsistent this is throughout the texts though. I can do 
a little searching to see how many times each is used and then we can 
decide what to do.

**Comment by balmas** [comment]
this is fixed at least for texts that are properly marked up in the v2.0-tei-test branch.  Change was to display both `<quote @rend='blockquote'>` and `<blockquote>` XML tags as HTML blockquote and to put " around the contents of `<quote>` tags that don't have @rend='blockquote'

Also cleaned up formatting of citation within or near a quote.

**Comment by monzug** [comment]
glad this one is fixed. can't wait to see it.

**Comment by balmas** [comment]
it's up on http://texts-test.alpheios.net but you might not be happy about all the other interface changes there... still very much a work in progress. Right now just trying to eliminate as much clutter as possible so that we can build it back up with designer input.

**Comment by monzug** [comment]
the top navigation is funky. are you still working on it? in this specific book (apologia) the top navigation goes to apologia then Pro Se De Magia Liber then apologia again when scrolling trough  the sections

**Comment by balmas** [comment]
yes there is something weird about apologia navigation. Still need to debug it :-)
