### ISSUE TITLE
XML Passage link produced wrong results

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#113]
I have a question on the XML version:
what's the difference btw Passage and Full text? they looked the same to me! Thanks

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios_nemo_ui/issues/46#issuecomment-487612968_

**Comment by balmas** [comment]
Passage is supposed to give just the XML of the passage being displayed, but it's not working correctly.

**Comment by monzug** [comment]
Thanks! I thought so.

**Comment by balmas** [comment]
ready for testing in beta environment.

**Comment by monzug** [comment]
verified in chrome and firefox. 
on iPhone xr, the text is displayed without the tags. it's ok on samsung
see screenshot
![IMG_3445](https://user-images.githubusercontent.com/41396793/57536682-a799f080-7312-11e9-986b-1baacea46a99.PNG)

**Comment by balmas** [comment]
@monzug this is up to the browser whether to offer to download the xml or display it and how to display it. There are some things I could try to force the browser to download rather than display it, but I don't think is critical. Going to go ahead and close this.

**Comment by monzug** [comment]
agree
