### ISSUE TITLE
Mobile: find a text and title are overlapping

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#116]
tested in latest build 1.0.0.6   - iPhone 5
see screenshot below

![IMG_3419](https://user-images.githubusercontent.com/41396793/56973832-a52dde80-6b3b-11e9-9ffa-629dc4e830a5.PNG)

**Comment by irina060981** [comment]
As search input was hidden - i simply fixed styles
![image](https://user-images.githubusercontent.com/12377640/57058449-6a6ea680-6cf3-11e9-9c83-b897de0d6c96.png)

**Comment by balmas** [comment]
Sorry about that! We can revisit when we reenable search after the beta.

**Comment by irina060981** [comment]
Merged and closed
