### ISSUE TITLE
My account from drop-down in top nav not working 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#118]
in Firefox and Chrome, logged in as user test in build 3.0.0.30
click on the arrow down and select My account. it does not work

**Comment by monzug** [comment]
also clicking on the down arrow of "Logged in as nickname" from main Menu does not work

**Comment by balmas** [comment]
yes, my account is not implemented yet... not really worth it until we have download/email of data I think.

**Comment by balmas** [comment]
but I agree the dropdown error next to the logged in as message in the menu should not be there.

**Comment by balmas** [comment]
assigning to @irina060981 . Let's take the "my account" link off for now, and fix the arrow in the menu. Thanks!

**Comment by irina060981** [comment]
Hide My account
And remove link from menu
![image](https://user-images.githubusercontent.com/12377640/57113875-f03d3100-6d89-11e9-887c-efaf0f8d67e4.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
live in texts-test.

**Comment by monzug** [comment]
verified
