### ISSUE TITLE
need to update the Help (Getting Started) for mobile

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#119]
while testing issue #98, I realize that we need to change also
Double-click on a word to retrieve morphology and short definitions. in
Tap on a word to retrieve morphology and short definitions.
I think we need to re-read all this Help text and adjust for the mobile app, if it hasn't been done yet.
do you know, @balmas ?

**Comment by balmas** [comment]
yes agree.

**Comment by irina060981** [comment]
I haven't found this text in Popup - `Double-click on a word to retrieve morphology and short definitions`
So I fixed that text, I found.
And also I have fixed styles a little.

**Desktop**
![image](https://user-images.githubusercontent.com/12377640/57053963-0341f980-6cd5-11e9-9bba-a1ef6527eb9b.png)

**Mobile**
![image](https://user-images.githubusercontent.com/12377640/57053969-0f2dbb80-6cd5-11e9-8d2d-dbf394955ca5.png)

Do you some other text, that should have separate versions for mobile and desktop that I missed here?

**Comment by monzug** [comment]
for the bibliography information on desktop, can we say just click? it's not a tap but it's not a double-click either... what would you say?

I was thinking of the Getting Started/Help from Info that needs to be updated for Mobile. I don't have the iPhone 6 available at the moment. do we display the following text in the Mobile app? if yes, this one needs to be updated.
Getting Started

Activate on a page with Latin, Ancient Greek, Arabic or Persian text.

Double-click on a word to retrieve morphology and short definitions.

Alpheios will try to detect the language of the word from the page markup. If it cannot it will use the default language.

Click the Options wheel to change the default language, default dictionaries or to disable the popup (set UI Type to 'panel').

Use the arrow at the top of this panel to move it from the right to left of your browser window.

You can reopen this panel at any time by selecting 'Info' from the Alpheios Reading Tools option in your browser's context menu.

Deactivate Alpheios by clicking the toolbar icon or choosing 'Deactivate' from the Alpheios Reading Tools option in your browser's context menu.

**Comment by irina060981** [comment]
Monica, on mobile it looks like this
![image](https://user-images.githubusercontent.com/12377640/57059874-90e41000-6cfa-11e9-9ff8-5c430ac1b094.png)

I could update the text - but it has rather more difficult structure
Icon + title + description
I like your text, but I don't not really know what to do with icons and title.
@balmas , what do you think?

**Comment by monzug** [comment]
it's not a substitute of the the current Help pop-up. it's the page that
shows up when you click on Info (help) from the overlay in the desktop and
it shows up in the panel

**Comment by monzug** [comment]
![help](https://user-images.githubusercontent.com/41396793/57063328-dc61d400-6c90-11e9-8e0e-45a71a162e48.JPG)

**Comment by irina060981** [comment]
oh, I see :)
I will check :)

**Comment by irina060981** [comment]
I don't  see the info panel
![image](https://user-images.githubusercontent.com/12377640/57066198-e9bda380-6d0e-11e9-9d3d-ca7224479b24.png)

**Comment by irina060981** [comment]
And on word click I could see only Morphology
![image](https://user-images.githubusercontent.com/12377640/57066262-15408e00-6d0f-11e9-875d-5aabe763d0ad.png)

**Comment by irina060981** [comment]
>for the bibliography information on desktop, can we say just click? it's not a tap but it's not a double-click either... what would you say?
I will fix it

**Comment by monzug** [comment]
the help page is generated from the Browse menu in mobile. if you do a lookup, the morphology page pops up, click on the browse icon on the top of pop-up. there is a drop-down menu which has Help. click on the icon and the Getting started panel is generated. uhm, complicated navigation for a getting started page.... (just a thought). let me know if you can't find it.

**Comment by irina060981** [comment]
oh, i have missed when this layout is changed :) Thank you, Monica :)

so you mean to adapt information here for the mobile?

**Comment by balmas** [comment]
I think we are going to get rid of the help in the mobile panel. See https://github.com/alpheios-project/components/issues/339#issuecomment-488809567

**Comment by monzug** [comment]
yes, I think the double-click and maybe we need a big rework to explain how
it works on the mobile (e.g. Options etc)

**Comment by monzug** [comment]
hahaha, even better!!!!

**Comment by irina060981** [comment]
@balmas , should I do anything else here? or it is done for the help popup in alpheios-nemo-ui

**Comment by balmas** [comment]
I don't think there is anything more to do on this one.
