### ISSUE TITLE
performance issues on scrolling

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#124]
from @monzug: checking performance on scrolling text + back arrow on the same text (in this case is http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi004.perseus-lat2/passage/6-10)
I noticed that there are some peak in CPU usage when using the back arrow after scrolling to the bottom of the text. is CPU usage at 50% ok? 
![IMG_3427](https://user-images.githubusercontent.com/644870/57099849-65a5f480-6ceb-11e9-9df9-d66982f79397.JPG)
![IMG_3426](https://user-images.githubusercontent.com/644870/57099850-65a5f480-6ceb-11e9-9ef7-8b34143da513.JPG)

**Comment by irina060981** [comment]
I have commented the infinite-scroll completely and the cpu picks are the same on simply load text (without any preload).
I think they are because of loading text from xml and scrolling is simply loading text too.

**Comment by monzug** [comment]
good to know. Thanks for investigating. My experience on CPU picks is when
going back using the back arrow so the text is already loaded, but it has
been split back in passages. do u see that?

**Comment by irina060981** [comment]
As it is not a single-page application, when you click a back link - it completely reloads the page.
And text is not preloaded there.
After clicking a back link, the page has got a new address, and all loading workflow steps are made the same way - as you simply reload the page.
So CPU picks should be similiar.

**Comment by monzug** [comment]
ah, ok. thanks.

**Comment by balmas** [comment]
I think this will improve once we add the PWA functionality to the application.

**Comment by balmas** [comment]
let's retest this once #9 is implemented.

**Comment by balmas** [comment]
well we won't do #9 in this release, but I think the inflection tables change did improve performance.  @monzug let me know what you think.

**Comment by monzug** [comment]
tested in text env on chrome and firefox. The scrolling has improved a lot.  in Firefox, I do still notice that the CPU usage is higher than in chrome. see screenshot
![cpu-firefox](https://user-images.githubusercontent.com/41396793/60273369-049e3580-98c4-11e9-8f9c-f51552d5d075.JPG)

**Comment by monzug** [comment]
retested again - looks pretty much the same and I haven't had any issue with delay
![ff-performance](https://user-images.githubusercontent.com/41396793/61818830-b7a87300-ae1f-11e9-9e76-af58224cf3fb.JPG)
