### ISSUE TITLE
need design for browse with genre...

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#127]
just realized we missed doing a design for the browse display when we have different genre categories as in Cicero

(http://texts-test.alpheios.net/collections/urn:cts:latinLit:phi0474)

**Comment by balmas** [comment]
it probably  just follow the same model as https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Browse/Book.png, with the first option being the group header, then from there expanding to book, etc.

**Comment by irina060981** [comment]
Would be the following
![image](https://user-images.githubusercontent.com/12377640/57301620-c8005a00-711c-11e9-8dec-37cd4da68731.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
can be tested at texts-beta

**Comment by monzug** [comment]
question on the alignment. in my screen the books are aligned differently. is the alignment based on the screen size?

**Comment by irina060981** [comment]
I have created this based on the following

**Mobile**
xs, sm - <=576px
**it is a list** 
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Collections/Works.png
![image](https://user-images.githubusercontent.com/12377640/57591988-9bfb3380-7577-11e9-8efb-5b38556cc10a.png)

**Desktop**
>576px
it is cards
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Collections/Works.png
![image](https://user-images.githubusercontent.com/12377640/57592019-bdf4b600-7577-11e9-8fbe-8788fbe1d276.png)

**Comment by monzug** [comment]
Thanks! I was just checking. all good here.
