### ISSUE TITLE
browse works - remove browse/read options

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#131]
@abrasax would like to remove the browse and read options from the browse works display, and just have the work titles linked to bring you to the first passage. Browse passages will still be available from the read display.

@irina060981 this will might require a little redesign of the browse works page --- I am not sure how the mini cards will look with just linked titles in them.  Let me know if you need advice on this.

**Comment by irina060981** [comment]
I think - if make it a little smaller it would be ok
![image](https://user-images.githubusercontent.com/12377640/57274947-3672f700-70e0-11e9-8bc7-f2a1bc8b2583.png)

**Comment by balmas** [comment]
that looks ok. But I think the links should be orange don't you?

**Comment by irina060981** [comment]
yes, you are right :)
I am just now working on aligning styles like links to styleguide and I missed links.

**Comment by irina060981** [comment]
Fixed and made this way
![image](https://user-images.githubusercontent.com/12377640/57299413-d4ce7f00-7117-11e9-9315-8b97cfb9fd00.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
can be tested at texts-beta

**Comment by monzug** [comment]
question on the alignment. in my screen they are all in one row and then one on second drow. Pls confirm if this is ok. Thanks
