### ISSUE TITLE
browse authors - remove number of works

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#132]
@abrasax would like us to remove the parenthetical number of works per author in the browse author display.

**Comment by irina060981** [comment]
Will look like the following
![image](https://user-images.githubusercontent.com/12377640/57275242-46d7a180-70e1-11e9-97f2-c07ae786434c.png)

**Comment by balmas** [comment]
that works.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
can be tested at texts-beta

**Comment by monzug** [comment]
verified
