### ISSUE TITLE
can we reduce the steps to browse a text in the text collections?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#14]
from the classical library collection, select Catullus then click on Browse (1). an other page is generated with Catullus as title and Carmina Browse (1) as book. Click on Browse again and an other page is generated with Carmina as title and Poems, Catullus with the options to Browse or Read. if I click on Read, I do finally open the Carmina poems. I think we have some redundant navigation. any way to reduce the steps to get to the poems?
this navigation works better when an author has multiple books.

**Comment by monzug** [comment]
an other example is the navigation for Ovid's Amores:
Home -  Text Collections - Classical Latin - Ovid - Amores - Amores

**Comment by balmas** [comment]
yes we should fix this.

**Comment by monzug** [comment]
I think the following page should include the browse and read links for each book so we reduce the steps. what do you think?

**Comment by balmas** [comment]
yes I agree we need to condense the steps. Need to investigate how much work it is.

**Comment by balmas** [comment]
implemented in the 2.0-tei-test branch.  Now the author level browse contains all works, with browse/read links for each. Breadcrumb may still need a little work still for best display.
