### ISSUE TITLE
hovering over copyright info button gives a light blue effect

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#142]
mobile only
when I hover over copyright info button, I can see a light blue color around it, sort of a 3d effect. both iPhone 5 and Samsung 5s

**Comment by irina060981** [comment]
@monzug, I think, you mean this
![image](https://user-images.githubusercontent.com/12377640/57427150-12412280-7266-11e9-8397-b0678342eed0.png)

this effetc is already fixed here - https://github.com/alpheios-project/alpheios_nemo_ui/pull/137
![image](https://user-images.githubusercontent.com/12377640/57427179-2dac2d80-7266-11e9-8392-23bfa5edf2ee.png)

**Comment by monzug** [comment]
Great! I'll reassign to myself for test case.Thanks
