### ISSUE TITLE
update tools icon in help

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#143]
per alpheios-project/components#515  we will have a new tools icon. We need to update the help popup to include this.  
![preview 2](https://user-images.githubusercontent.com/644870/57388649-a0de7280-7186-11e9-8ddd-9a1cc967e8fe.png)

**Comment by irina060981** [comment]
Changed icon in help popup:
![image](https://user-images.githubusercontent.com/12377640/57427051-84fdce00-7265-11e9-82c9-c71e7cf023c2.png)

**Comment by irina060981** [comment]
merged and closed
