### ISSUE TITLE
Reskin options: smaller font than other options

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#149]
I found a note from last week about reskin option: "just noticed that the large reskin option in mobile (Samsung 5mini) is truncated, specially when I select large". Glad this is not longer reproducible as the reskin option have smaller fonts compare with the other options. I looked for an issue but couldn't. Pls confirm this is ok. Thanks.

 ![size-related-width-page](https://user-images.githubusercontent.com/41396793/57570409-a11d7e80-73cf-11e9-86f0-723928bcb80c.JPG)

**Comment by balmas** [comment]
I think this is okay. Closing.

**Comment by monzug** [comment]
cool.thanks
