### ISSUE TITLE
Caesar: title should be De bello civili and De bello Gallico

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#15]
both books are in Latin, so I think titles should be in the original language as in Perseus. there are at least 3 different tags for title in de bello gallico:

from titleStmt:
1) <title type="work" n="Gal.">De bello Gallico</title>

from sourceDesc:
2) <title>C. Iuli CommentariiRerum in Gallia Gestarum VII A. Hirti Commentarius VII</title>
3) <title>Scriptorum Classicorum Bibliotheca Oxoniensis</title>
we are using the last two.

also, in the top navigation for de bello gallico, we use  Gallic War, C. Iuli Caesaris Commentarii rerum in Gallia gestarum VII A. Hirti Commentarius VIII 
so it looks like this:
Home - Text Collections - Classical Latin - Caesar, Julius.  - Gallic War - Gallic War, C. Iuli Caesaris Commentarii rerum in Gallia gestarum VII A. Hirti Commentarius VIII 
in de bello civili, we have the following:
Home - Text Collections -  Classical Latin - Caesar, Julius.  - Civil War - De Bello Civili

**Comment by balmas** [comment]
Submitted PR to PerseusDL https://github.com/PerseusDL/canonical-latinLit/pull/295

**Comment by balmas** [comment]
the metadata is fixed now, but we need to fix #35 for it to show up.

**Comment by balmas** [comment]
can be tested now.
