### ISSUE TITLE
style guide overrides

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#154]
a few requests from @abrasax 

- section headers/next level smaller
- text size larger with slightly more space in between lines
- line numbers smaller

**Comment by irina060981** [comment]
I have decreased from `font-size` 22px to 20px for section headers and line numbers:
![image](https://user-images.githubusercontent.com/12377640/59236611-5f842b80-8c3a-11e9-88de-7564bf964c02.png)

And have increased `font-size`
 to 18 from 16, `line-height` from 1.2 to 1.4

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test embed-lib 1.0.0.23

**Comment by monzug** [comment]
I confronted the texts-test embed-lib version with the texts-beta. In Firefox and Chrome (desktop) looks good.
in mobile (Safari), I have the impression that the line numbers in text version (most recent) are bold and bigger than in  beta version (older). see below 
![IMG_3627](https://user-images.githubusercontent.com/41396793/59772466-d001fc80-9279-11e9-95e8-ec4c514e78e9.PNG)
![IMG_3626](https://user-images.githubusercontent.com/41396793/59772467-d001fc80-9279-11e9-9b75-08d075d3c622.PNG)

**Comment by irina060981** [comment]
@monzug , you are right - t
- I have made the line numbers smaller according to the task
and also I remove bold - because in style guide smaller font size is not bold

But may be I should return bold weight.

**Comment by balmas** [comment]
I think they should not be bold.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
ok.
