### ISSUE TITLE
change help icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#156]
requested by @abrasax 

Can we use a ? instead of the i for the help icon on the navigation header bar

**Comment by irina060981** [comment]
I have taken ? from the same font Segoe UI
![image](https://user-images.githubusercontent.com/12377640/57692182-7c543000-7689-11e9-9b86-84d6547d14d0.png)

**Comment by irina060981** [comment]
Merged and closed
