### ISSUE TITLE
mobile - modify navbar when in landscape with alpheios panel open

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#158]
The design called for the navbar to change itself to remove everything but the menu and a tip to close the panel to resume full screen when the panel was opened in landscape mode. 

![Landscape-Mode-Panel-Open](https://user-images.githubusercontent.com/644870/57647167-47b07d80-7590-11e9-9720-ad19316c63c7.png)

I don't know how difficult this will be to do. I think a cheap way to do it would be to have alpheios add a data-attribute to the body of the page when the panel is open in landscape mode.  @kirlat and @irina060981 what are your thoughts?

(See also related item https://github.com/alpheios-project/components/issues/397)

**Comment by balmas** [comment]
copying some notes from alpheios-project/components#564

From @kirlat 

>The current version of components, when present, sets a data-ap-screen-orientation="landscape" data attribute of an html element that contains the current screen orientation. It updates every time orientation changes.
There is also an orientation change event fired by the Platform class instance (UI controller has it in the platform prop) when orientation is switched. We can subscribe to it if we need to detect an orientation change dynamically.

And @irina060981 
>I tried to look at it today - it has a direct style property - padding-left: 50%
so as we change layout via media-query - it doesn't properly work

**Comment by balmas** [comment]
I'm taking this out of the beta. We will fix it later.

**Comment by irina060981** [comment]
Would be this way

![image](https://user-images.githubusercontent.com/12377640/58479381-8bfc6a00-819b-11e9-8b20-60b1ff44f88a.png)

![image](https://user-images.githubusercontent.com/12377640/58479410-96b6ff00-819b-11e9-88ed-864d85630070.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
can be tested in texts-beta embed-lib 1.0.0.18

**Comment by monzug** [comment]
so, if I scroll the text, the main menu icon and book title disappear from the top navigation, both on iPhone xr and Samsung 5 mini. see screenshots
![IMG_3501](https://user-images.githubusercontent.com/41396793/58487539-bd424f00-8135-11e9-852d-2c3447ebf0ab.jpg)
![IMG_3500](https://user-images.githubusercontent.com/41396793/58487541-bd424f00-8135-11e9-824c-c0702e17bfb0.jpg)
on iphone xr
![IMG_3503](https://user-images.githubusercontent.com/41396793/58487686-098d8f00-8136-11e9-9c23-c2fea01f77c2.PNG)

**Comment by balmas** [comment]
ok, I see that. But I think it's okay for the beta.

**Comment by balmas** [comment]
let's enter a new issue for it.

**Comment by monzug** [comment]
ok. will do it.

**Comment by monzug** [comment]
issue #170
