### ISSUE TITLE
Show Latin Titles for all Works

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#16]
e.g. we use Ovid and not Ovidius like in Perseus. 
also his books are a mixed of English and Latin titles.
in Perseus title is Tristia, in Alpheios title is Sorrows
in Perseus title is Ex Ponto, in Alpheios title is Letters from the Black Sea
in Perseus title is Fasti, in Alpheios title is Book of days

e.g. Horace should be Horatius  and ars poetica should be De arte poetica liber
e.g. Pliny the elder and Pliny the younger, Vergil etc

I am not sure if this is intentional as some authors names are translated in English. Perseus is more consistent regarding the use of Latin vs English, except for Pliny the elder and the younger.

**Comment by balmas** [comment]
None of this is probably intentional, just inconsistencies in the Perseus data workflow.  I think ideally we should have Latin titles for all of the works, but this might be a pretty big job.   Will leave this in and we'll see what we have time to fix.

**Comment by balmas** [comment]
Discussed with @abrasax . We want to display Latin titles. Will reduce release texts to subset to make it manageable.

**Comment by balmas** [comment]
All Latin works should now use Latin titles in all displays. Greek works use mostly English titles. For Homer' works I am using the greek titles on the text display. I am not sure what the final decision on that will be so am waiting to update the other Greek texts.
