### ISSUE TITLE
Read is not properly alligned in Carmina (desktop only) 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#161]
go to Catullus, Carmina poem 68b.31-60
http://texts-beta.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/68b.31-68b.60
in Firefox (and Chrome), the last Read icon is not aligned with the previous one as there is an extra digit
in Safari (Mac), it's the first one that is not aligned as the others (or the other way)
see screenshots
![allignment-read](https://user-images.githubusercontent.com/41396793/57706437-beeb1d80-7633-11e9-939a-b941d5bdd229.JPG)

**Comment by monzug** [comment]
Safari (Mac)
![Screen Shot 2019-05-14 at 4 25 14 PM](https://user-images.githubusercontent.com/41396793/57706543-3d60b300-7666-11e9-903a-44001dad66f8.png)

**Comment by monzug** [comment]
Irina, if it's a super easy fix.... Thanks

**Comment by irina060981** [comment]
Yes, it is really a small fix :)

![image](https://user-images.githubusercontent.com/12377640/57765252-6ce7ec00-7748-11e9-9516-f02937c3f94b.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
Irina, Thank you! does it apply to all the situation in which the passage
numbers are 1 or 3 digits?

**Comment by irina060981** [comment]
I have selected the width according to this max - xxx.xxx (it is made manually - not real format)

![image](https://user-images.githubusercontent.com/12377640/57773068-7b3f0380-775a-11e9-90fb-fddb1eea286a.png)

@monzug , is it enough? what do you think?

**Comment by monzug** [comment]
I would think so. Thanks

**Comment by balmas** [comment]
ready for testing in beta environment.

**Comment by monzug** [comment]
looks good. Thanks
