### ISSUE TITLE
Minor issue: tools menu partially visible in landscape view

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#162]
iPhone xr:
in landscape view, the tools menu is very difficult to scroll down to user word list, user info, options. to repro, login and lookup for a word, so the tools menu is populated by all the options. in partial view (not expanded), it bounced back from Options to Browse inflection table, so it's very difficult to select Options.
the workaround is to expand the pop-up in landscape view or to go in normal view.
![IMG_3453](https://user-images.githubusercontent.com/41396793/57710935-daf2bd00-763b-11e9-994e-d99f2e7bb2ba.PNG)

**Comment by balmas** [comment]
I think this one will be made obsolete by alpheios-project/components#564

**Comment by monzug** [comment]
excellent.

**Comment by balmas** [comment]
closing. test with alpheios-project/components#564

**Comment by monzug** [comment]
yes, gone!
