### ISSUE TITLE
deploy under https

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#164]
in preparation for eventual PWA functionality, we should deploy the beta under https from the start.

**Comment by balmas** [comment]
this is now implemented. You can still access http://texts-beta.alpheios.net but if you try to login it will return you to https://... .  You can also just start at https://texts-beta.alpheios.net.

**Comment by monzug** [comment]
login from http://texts-beta.alpheios.net, it will switch to a secure site: https://texts-beta.alpheios.net
tested on mobile and desktop
