### ISSUE TITLE
authors names: some oddities

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#17]
Quintilian is in parenthesis in text collection, why?
[Quintilian]

e.g. Ausonius, Decimus Magnus has a dot in the text collection
Ausonius, Decimus Magnus.

also Marcellinus, Caesar, Claudianus and few others.

Seneca, Tacitus, Valerius  (who also have first and last name) do not have a dot.

**Comment by balmas** [comment]
Submitted https://github.com/PerseusDL/canonical-latinLit/pull/290 for [Quintilian]

**Comment by balmas** [comment]
submitted https://github.com/PerseusDL/canonical-latinLit/pull/292 to remove . from author names

**Comment by balmas** [comment]
PR was merged.
