### ISSUE TITLE
wording change for help

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#171]
requested by @abrasax 

1.  "Word interaction"  might better be Word Selection

2. "Navigate what Alpheios has to offer (top left)"  might be better as "See which texts are currently available"

3. Browse Passages: "Navigate the current work's passages (top right)" . might be better as             "See a table of contents for the current text"

**Comment by balmas** [comment]
But note that in #188 @abrasax asked to change back from "word interaction" to "word selection"

**Comment by balmas** [comment]
qa-3.0.0.49/components 1.2.12

**Comment by monzug** [comment]
can we add that usage examples is only for latin? maybe next to it in parenthesis

**Comment by balmas** [comment]
> can we add that usage examples is only for latin? maybe next to it in parenthesis

ok. I debated that, left it out, but think you're right.

**Comment by balmas** [comment]
I put 'Latin' before usage examples, because otherwise it wasn't clear if it referred to the whole sentence or just the usage examples.

**Comment by monzug** [comment]
this is for mobile. we do need to update few thing in the help on web ext (e.g. add the Ethiopic language, double-click  to add lemma and Latin usage examples, set ui type to panel, etc, default language been latin,) etc - do we have an issue for this?
also, shall we say that as default position for panel is left, we move from the left to the right?

**Comment by balmas** [comment]
we do have an issue for the help on the webext - it's alpheios-project/components#615.  I don't know if we need mobile specific help for it though, because the info panel isn't shown on mobile. Please wait to test again with the next build. 

But one point re the languages -- I am thinking maybe to just drop the list of languages from the info panel help. What do you think?

**Comment by monzug** [comment]
that would be better and more stable.

**Comment by balmas** [comment]
ok, for the arrow, I think maybe I'll just change it to "Use the arrow at the top of this panel to swap positions between the right and left side of your browser window."

**Comment by balmas** [comment]
can we close this one now for the texts env?
