### ISSUE TITLE
add cookie consent

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#176]
use the open source cookie consent library to add cookie consent banners https://github.com/osano/cookieconsent

**Comment by irina060981** [comment]
Added
![image](https://user-images.githubusercontent.com/12377640/59512510-398dae00-8efc-11e9-8708-1438ec91ed95.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
let's hold off on testing until #190 is done

**Comment by balmas** [comment]
ready for testing at texts-test

**Comment by monzug** [comment]
looks good. is it ok to have the two banner overlapping in this situation? see screenshot

![IMG_3638](https://user-images.githubusercontent.com/41396793/59976928-1bc5e600-9599-11e9-9fb2-a452641873bc.PNG)

**Comment by balmas** [comment]
oh that is kind of awful. But  I think we will remove the feedback popup for release anyway so let's not worry about it.

**Comment by balmas** [comment]
> oh that is kind of awful. But I think we will remove the feedback popup for release anyway so let's not worry about it.

In the meantime, I have increased the delay before the survey popup shows, to 30 seconds. So this should prevent conflict.
