### ISSUE TITLE
No clear "back to start page" navigation

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/alpheios_nemo_ui#178]
When working with the Alpheios Reader, I discovered that it was not evident for me how to return back to the start page of the app (i.e. to the `/` page). 

This is how the app's menu looks, and, on my opinion, it is not clear that we have to use a "Language" menu item for that. 
![image](https://user-images.githubusercontent.com/18631055/59358764-33ea6980-8d3e-11e9-88e5-f723ef80166b.png)

Maybe we should add something more self-evident, such as "Start page", or "Index", or anything like that?

**Comment by balmas** [comment]
@monzug what do you think?

**Comment by monzug** [comment]
Uhm, the first time I used the new version, I didn't have any problem as Language was the only option available. It might be a problem for some users, but I don't think so. Language by itself is in the style guide. Maybe changing to "Select a language to start", if it's not too long.

**Comment by balmas** [comment]
I don't know. The design did call for the Language menu item but that wasn't really put to any usability tests. On the desktop, the Alpheios icon in both the menu and in the top header bring you back to the start page too.  But those options aren't there on mobile. It's a little inconsistent.  @abrasax  do you have an opinion on this?

**Comment by kirlat** [comment]
It's probably just me, but looking at the menu I would think that "Go to Alpheios.net" is the start page of the app. It has an arrow, and even thought it is pointing in the upward right direction, it probably might still be associated with the back to home button (especially since there are no other arrows there to compare their directions). Only the fact that I knew that Alpheios.net is a different site stopped me from using this menu item as a home button.

For me it was not evident that Language === Start page. Language is under Collections, so I would think it's just one of the collections available. But again, this can be personal.

**Comment by monzug** [comment]
we can add extra space above alpheios.net link to better mark the separation from current site. as per Language == Start page, it's the only option available and if you close the main menu, you are on the select a language page.  I was suggesting to change Language to 'Select a language to start' but giving second thoughts, it's redundant. A nested redesign? I don't think it would look good on the mobile.
I remember having some troubles with Language in main menu versus Language/Authors in top nav.

**Comment by balmas** [comment]
@abrasax requests that we just leave this the way it is too. I will close it.
