### ISSUE TITLE
remove the reference to the volume from the title in the Rerum Gestarum by Marcellinus

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#18]
Few things here:
1) in perseus I could not find any reference to the volume 1 to 3 but I did find it in Loeb Classical library, Volume I is for Books 14-19
Volume II is for Books 20-26
Volume III is for Books 27-31. Excerpta Valesiana
not sure if it would be better to remove the reference to the volume from  the title or to split the book in volumes.

2)  book val1 and book val2 should have a title like in Perseus:
<head>Anonymi Valesiani Pars Prior: origo Constantini Imperatoris</head> for Book val1 and 
<head>Anonymi Valesiani pars posterior: Chronica Theodericiana</head>for Book val2

3) At the beginning of every chapter there is a "subtitle", sort of description of the chapter. I found a note in the xml that says: e.g.     for <head>Galli Caesaris saevitia. 
<note>These summaries, which are not the work of
                           Ammianus but of some early editor, are put for convenience at the
                           beginning of each chapter. Usually the summaries of each book are put all
                           together at the beginning of that book, or (e.g. by Eyssenhardt) the
                           summaries of all the books are collected at the end of the entire
                           text.</note></head>
note that these "subtitles"  are visible in perseus and also used in Loeb Classical library. we are not showing them. the tag is note.

**Comment by balmas** [comment]
> 2\. book val1 and book val2 should have a title like in Perseus:
> 
> Anonymi Valesiani Pars Prior: origo Constantini Imperatoris for Book val1 and Anonymi Valesiani pars posterior: Chronica Theodericianafor Book val2

this will be addressed via #23

**Comment by balmas** [comment]
>1. At the beginning of every chapter there is a "subtitle", sort of description of the chapter. I found a note in the xml that says: e.g.     for Galli Caesaris saevitia.
   These summaries, which are not the work of
   Ammianus but of some early editor, are put for convenience at the
   beginning of each chapter. Usually the summaries of each book are put all
   together at the beginning of that book, or (e.g. by Eyssenhardt) the
   summaries of all the books are collected at the end of the entire
   text.
   note that these "subtitles"  are visible in perseus and also used in Loeb Classical library. we are not showing them. the tag is note.

This is split from this item as transform bug #24

**Comment by balmas** [comment]
titles are the remaining data issue - submitted fix in https://github.com/PerseusDL/canonical-latinLit/pull/290

**Comment by balmas** [comment]
merged.
