### ISSUE TITLE
texts navbar: change icon order

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#181]
@abrasax requests that the browse icon come before the help icon on the texts navbar (so that help is always just to the left of tools)

**Comment by irina060981** [comment]
I have changed on reader page and on browse page too - because they both have an icon after help.

![image](https://user-images.githubusercontent.com/12377640/59510966-6c35a780-8ef8-11e9-9fdc-a8add7e44f00.png)

![image](https://user-images.githubusercontent.com/12377640/59510980-735cb580-8ef8-11e9-80ca-f348e296592d.png)

There is also a hidden block for reading tools - I have placed them before Help icon too.

**Comment by balmas** [comment]
ready for testing at texts-test

**Comment by monzug** [comment]
Desktop works as described. 
How about mobile? in the Reader, I can see the Help icon as last icon on the nav bar (also on the right of reading tools). on Collections, the Help icon is on the left of Reading tools.
see screenshot
Collection
![IMG_3623](https://user-images.githubusercontent.com/41396793/59766193-9e833400-926d-11e9-90ea-3d69bf30ccfe.PNG)
Reader
![IMG_3624](https://user-images.githubusercontent.com/41396793/59766521-63cdcb80-926e-11e9-880f-062bbba6cf73.PNG)

**Comment by irina060981** [comment]
oh - I have missed collection mobile navbar, thanks @monzug - will fix it!

**Comment by monzug** [comment]
No problem. However, I am not sure about the order. should Help icon be the last or should go as said above in the issue:  "that help is always just to the left of tools"?

**Comment by irina060981** [comment]
@monzug , may be then - I should make the other change and to place help icon before tools on texts mobile page? I think I haven't correctly read the task - missed "that help is always just to the left of tools"

**Comment by monzug** [comment]
let's have @balmas giving the last word. I am not so sure either.

**Comment by balmas** [comment]
I think the order should always be, left to right, help then tools.  Any additional icons go to the left of help

**Comment by irina060981** [comment]
merged and closed

**Comment by monzug** [comment]
verified.
