### ISSUE TITLE
drop hints text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#183]
@abrasax requests that we remove the following hints text

"Select a language" (on collections level 1)
"Select an author" (on collections level 2)
"Select a work" (on collections level 3)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test

**Comment by monzug** [comment]
tested in mobile and desktop - above hints are out

**Comment by monzug** [comment]
how about Select a passage in Browse passage  (e.g. https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg006.alpheios-text-grc1/references)?

**Comment by balmas** [comment]
ah yes, good point. thanks @monzug .  Passing back to @irina060981 for that.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
verified
