### ISSUE TITLE
activate breadcrumbs on collections

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#184]
the breadcrumbs Language/Author/Work should be made active now if possible

**Comment by irina060981** [comment]
@balmas , what do you mean - to make active?
They are clickable already.
I checked here https://texts-beta.alpheios.net/collections/urn:cts:greekLit:tlg0012 , for example

**Comment by balmas** [comment]
Oh that's weird. You're right. It seemed they weren't working on @abrasax 's display but they do appear to be working so never mind :-)
