### ISSUE TITLE
move bibliographic icon to after the title

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#185]
@abrasax  requests that we move the bibliographic icon to after the title/author text rather than before it.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test

**Comment by monzug** [comment]
yes, it's there. tested in mobile and desktop (Firefox and Chrome)
question: should we move the author/text slightly on the left side? there is space to align with the menu button

**Comment by balmas** [comment]
yes, I think you are right.

**Comment by irina060981** [comment]
I have forgotten to fix styles after  moving the icon to the right, great catch, @monzug !

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
verified
