### ISSUE TITLE
Horace: Satires and Carmina titles need to be fixed.

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#19]
1) the title should be <title  type="work"> Satyrarum libri  closed title, as in Perseus
not  The works of Horace translated literally into English prose Volume 2 as this is not a translation, I believe.

2) the subtitle of each section should be bold as in Perseus and in Scaife
e.g. Ad Maecenatem:  Omnibus, maxime vero avaris, sortem suam gravem esse should be bold

<div xml:lang="lat" type="edition" n="urn:cts:latinLit:phi0893.phi004.perseus-lat2"><div type="textpart" n="1" subtype="book"><div type="textpart" n="1" subtype="poem"><head>Ad Maecenatem:  Omnibus, maxime vero avaris, sortem suam gravem esse.  
 
subtitles are missing from Loeb Classical library, except for first chapter (and it's different from perseus), it could be a different edition.

**Comment by monzug** [comment]
also the book Odes, Horace Odes and epodes should be Carmina - in the xml we have Carmina in the title tags

**Comment by balmas** [comment]
title is a data issue, submitted fix in https://github.com/PerseusDL/canonical-latinLit/pull/289

section heads should be addressed with #23

**Comment by balmas** [comment]
Satires title fix is merged. Missed the one for Carmina. Will need to do a new PR for that.

**Comment by balmas** [comment]
Submitted fix to PerseusDL corpus https://github.com/PerseusDL/canonical-latinLit/pull/295

**Comment by balmas** [comment]
data is fixed but we need to wait for #35 and #40 to test

**Comment by balmas** [comment]
can be tested now.

**Comment by monzug** [comment]
titles look good now but found a bibl source which needs some rework, what do you think?
Ars Poetica
in Perseus, the title is Q. Horatius Flaccus (Horace), De Arte Poetica liber and C. Smart editor
in Alpheios  (and Scaife) we have in bibl source Ars Poetica, The works of Horace translated literally into English prose Volume 2, Horace, creator; Smart, Christopher, 1722-1771, editor

**Comment by balmas** [comment]
this is in https://github.com/alpheios-project/canonical-latinLit/commit/37b7b6ce36ed3b966fb78765bd16795490830935

**Comment by monzug** [comment]
verified
