### ISSUE TITLE
styling of cookie consent banner

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#190]
I think we just need to add the .cc-floating class specifier along with .cc-banner because it automatically switches to floating on mobile. (this is what I did for the landing page anyway in https://github.com/alpheios-project/landing-page/commit/442d5034209d85dd86d37582ccf51fd8c0a0bef7

**Comment by balmas** [comment]
also need to:
1. style the visited and activate state of the cc-link the same as unvisited
2. change the href of the Learn More link to https://alpheios.net/pages/privacy-policy

**Comment by irina060981** [comment]
@balmas , should I change these styles too:
```
background: $alpheioscolorneutraldark;
color: $alpheioscolorneutrallightest;
```
?

**Comment by balmas** [comment]
@irina060981 I don't know. I really liked the way it looked with the dark color, but we couldn't use that on the landing-page website because we use that color there for some sections, and it got lost. That's the only reason I changed it. I suppose it make sense to keep it consistent across the applications though. What do you think?

**Comment by irina060981** [comment]
If to be honest, I don't think we should keep it the same for landing page and for texts reading center, because they have different background , and the color of the banner should look well with the background I believe.
I suggest then to keep them slightly different.

**Comment by balmas** [comment]
ok.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test

**Comment by monzug** [comment]
cookie consent banner style is the same on the text env, it does change when I link to https://alpheios.net/pages/privacy-policy/, the background is gray and not dark color.
in landscape view, the banner is way too big. any way to make it smaller?
see screenshot
![IMG_3637](https://user-images.githubusercontent.com/41396793/59976859-1ddb7500-9598-11e9-9ff0-204d8189ab6e.PNG)

**Comment by balmas** [comment]
hmm, I forgot about the link from one to the other, @irina060981 maybe we should keep the color gray across both then? As for the mobile display, I think it isn't detecting mobile properly there, because it should be a popup.

**Comment by irina060981** [comment]
Agree, if we have cross-links - we should make it consistent - will change to gray then.

**Comment by irina060981** [comment]
merged and closed

**Comment by monzug** [comment]
verified on mobile and desktop: gray banner
