### ISSUE TITLE
missing poem identifier

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#193]
while testing section and line numbers, I come across Elegiae - Propertius, Sextus
http://texts-beta.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.perseus-lat3/passage/1.1

as we do not break the text between poems (poem 1, poem 2, poem 3 etc) when scrolling down, the line numbers go from 5 to  35 and then start again at 5 which is poem 2. In perseus, it's more evident that you are going from poem 1 to poem 2.  Should we add a break between poems?

see screenshots

![elegiadi](https://user-images.githubusercontent.com/41396793/57777267-798c2600-76ef-11e9-81ba-ddf49c94737c.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios_nemo_ui/issues/86#issuecomment-492643284_

**Comment by balmas** [comment]
keeping track of my investigation here:

the problem is that the code that I was using to try to calculate whether or not we've crossed citation levels when we retrieve a passage is flawed. This is the `AlpheiosNemoUInew_level` method. It really only works in the following scenarios:

1. a citation scheme of at least 3 levels where the 2nd level is the one being crossed (such as in Caesar, when you go from e.g. 1.1.1 - 1.2.8)
2. a citation scheme of at least 2 levels where the 1st level is being crossed  (such as in Propertius when you go from 1.1-2.2)

Not positive we can hack this further without changing either the texts or the underlying capitains library. Still pondering.

**Comment by monzug** [comment]
When the 5 (only 5) is displayed, count 4 line back and add a break or an empty line. would it be difficult to implement?

**Comment by monzug** [comment]
I did also notice that in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.perseus-lat3/passage/1.11, there is line 15 and below line 10. I checked on Scaife and I could see the problem there. the lines are messed up, basically in Scaife they go from 8 to 15, 10, 9, 11, 12, 13, 14 and 16. same in latin library and Phi latin text and Perseus. interesting that in Perseus there are two translations, the one from Kats does not have this problem, so I guess it's due to the translation of Mueller that everybody is using.

**Comment by balmas** [comment]
registered the line numbering as a separate issue #204

**Comment by balmas** [comment]
> When the 5 (only 5) is displayed, count 4 line back and add a break or an empty line. would it be difficult to implement?

That might be possible. The bigger problem is that we want to do different things depending upon the citation scheme and state of the markup of the text. Some texts have section headers already in them some don't and so on...

**Comment by balmas** [comment]
this is also the cause of the problem reported in #232: 

Jumping from one section of Carmina to an other using the Find passage feature in Carmina, Callustus e.g. https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/1?subreference=1, somehow we do not display the section breakers
tested

**Comment by balmas** [comment]
fixing this requires changes to the underlying capytains library, including the fix for related item #23, which are out of scope for this release.

The best I can do is deal with this on a text-by-text basis by inserting the section heads directly in the underlying xml where needed.  I have done this now for Propertius and Catullus. We will use the Alpheios editions of these texts for now.

**Comment by balmas** [comment]
per discussion with @monzug should also updated bibliographic information of propertius with details of which passages have trees.

**Comment by monzug** [comment]
looks good. I can still see the problem of the lines messed up (e.g. line 15 before line 10 in 1.11) but that's the translation
