### ISSUE TITLE
Apuleios: Apologia is repeated twice in the navigation + missing UNICODE for Greek characters

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#20]
the book title Apologia is repeated twice (same as in Scaife): Apuleius /  Apologia / Apologia, Apologia

also, Greek characters are not displayed in Unicode
e.g. there is a sentence that in Perseus is displayed correctly in Greek but in both Scaife and Alpheios looks like the following:

ou)/ toi a)po/blht' e)sti\ qew=n e)rikude/a dw=ra,o(/ssa ken au)toi\ dw=sin, e(kw\n d' ou)k a)/n tis e(/loito,

it should be:
οὔ τοι ἀπόβλητ᾽ ἐστὶ θεῶν ἐρικυδέα δῶρα, ὅσσα κεν αὐτοὶ δῶσιν, ἑκὼν δ᾽ οὐκ ἄν τις ἕλοιτο,

e.g. Greek word a)pori/as should be ἀπορίας

<foreign lang="greek">οὔ τοι ἀπόβλητ᾽ ἐστὶ θεῶν ἐρικυδέα δῶρα,</foreign><foreign lang="greek">ὅσσα κεν αὐτοὶ δῶσιν, ἑκὼν δ᾽ οὐκ ἄν τις ἕλοιτο,</foreign>

vs

<foreign xml:lang="grc">ou)/ toi a)po/blht' e)sti\ qew=n e)rikude/a dw=ra,</foreign><foreign xml:lang="grc">o(/ssa ken au)toi\ dw=sin, e(kw\n d' ou)k a)/n tis e(/loito,</foreign>

**Comment by balmas** [comment]
these are bugs in the data. Submitted to Perseus DL as pull requests https://github.com/PerseusDL/canonical-latinLit/pull/288 and https://github.com/PerseusDL/canonical-latinLit/pull/287

**Comment by balmas** [comment]
hmm. data fix was merged, but now something weird - the work and edition titles seem to be alternately showing 'Pro Se De Magia Liber' instead of 'Apologia' as the title. Need to investigate this.  Might be a result of application code changes or might be a remaining data problem.

**Comment by monzug** [comment]
I just noticed that you also have reported this. I did in #11 
the top navigation is funky. are you still working on it? in this specific book (apologia) the top navigation goes to apologia then Pro Se De Magia Liber then apologia again when scrolling trough  the sections

also: also, there is still Unicode issue at the bottom of http://texts-test.alpheios.net/text/urn:cts:latinLit:phi1212.phi001.perseus-lat1/passage/27-31
<quote rend="blockquote" xml:lang="greek">
<lb/>
th=| plei=sta fe/rei zei/dwros a)/roura
<lb/>
fa/rmaka, polla\ me\n e)sqla\ memigme/na, polla\ de\ lugra/,
</quote>

**Comment by monzug** [comment]
again, I did not close it or not intentionally.

**Comment by monzug** [comment]
Apologia has been removed completely and the new title is in latin  Pro se de magia liber
However, I am not sure if the source content is correct. I compare with Scaife and Perseus and does not look the same, unfortunately cannot check the source.
in Alpheios:  Apologia, Apuleius. Apulei Opera Quae Supersunt, Vol. II, Fasc. I. Helm, Rudolf, editor. Leipzig: Teubner, 1912.
in Perseus:  Apuleius. Apulei Platonici Madaurensis, Pro se de magia liber (Apologia). Rudolf Helm. Lipsiae : B.G. Teubneri. 1912. Keyboarding. 
in Scaife:  Apologia, Apologia
Apuleius, creator; Helm, Rudolf Wilhelm Oskar, 1872-1966, editor

**Comment by balmas** [comment]
The remaining issue here is that we aren't sure what to do when there are two titles with the same language in the metadata. This work has:

```
 <ti:title xml:lang="lat">Apologia</ti:title>
<ti:title xml:lang="lat">Pro Se De Magia Liber</ti:title>
```
I think the data here is okay, but the application needs to handle this better. Am going to close this item and enter a new one for that.
