### ISSUE TITLE
drop font-awesome import

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#203]
I think we don't need this anymore and it adds a little bit to the download time and size.  @irina060981 please confirm that we don't need it. I think it was leftover from before the redesign. Thanks!

**Comment by irina060981** [comment]
I have made a searcg by `fa-` in all source files - and found nothing.
I removed the link - works well!

**Comment by irina060981** [comment]
It is really a very small fix - I merged it without a review

**Comment by irina060981** [comment]
Merged and closed
