### ISSUE TITLE
browse passage oddity in Firefox

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#206]
reported by @monzug when browsing through passages there is a number appearing on the lower left of the screen in firefox

**Comment by monzug** [comment]
actually it's on mobile too (iPhone xr, Samsung 5) and in chrome too on desktop. could it be a counter for how many times I reload the page?

**Comment by balmas** [comment]
oh.. maybe I think I had some debugging code like that in there at one point... maybe I never took it out :-)

**Comment by monzug** [comment]
could be. I noticed it yesterday, though

**Comment by balmas** [comment]
this was a debugging print in the template which includes the survey sparrow embedded survey. it's removed now.

**Comment by monzug** [comment]
gone. tested in embed-lib-1.0.0.28 (with components 1.2.2)
