### ISSUE TITLE
add Ovid texts

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#209]
we need to add Ovid's texts for the release

**Comment by balmas** [comment]
Ok, Ovid is there. Metamorphoses is a merge of the Alpheios version of the Perseus one, with trees available for lines 1.1 - 1.9 and 1.163-1.778.

**Comment by monzug** [comment]
we should add some info that diagrams are available only for most of book.

**Comment by balmas** [comment]
bibliographic metadata now indicates which lines are annotated.

**Comment by monzug** [comment]
trees are gone in Metamorphoses, ?

**Comment by balmas** [comment]
sorry, I had to tweak the deployment environment to make sure we always get the Alpheios version of the text and not the Perseus one. It should be the right one now.

**Comment by monzug** [comment]
yes, it does
