### ISSUE TITLE
Caesares, Ausonius, with an English translation Vol 1 should have a different title

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#21]
book title should be Ausonii de XII Caesaribus per Suetonium Tranquillum scriptis as in Perseus for urn:cts:latinLit:stoa0045.stoa002.perseus-lat2

also, we are ignoring all the tags with head as subtitles of the sections, which are displayed in Perseus
e.g. in Perseus  book 1 is Monosticha with sections  
AUSONIUS HESPERIO FILIO S. D.
MONOSTICHA DE ORDINE IMPERATORUM
DE AETATE IMPERII EORUM MONOSTICHA
DE OBITU SINGULORUM MONOSTICHA 

these are equal to Poem 1 to Poem 4 in Alpheios

e.g. in Perseus book 2 is Tetrasticha with sections
section praef
IULIUS CAESAR
OCTAVIUS AUGUSTUS
TIBERIUS NERO
CAESAR CALIGULA
CLAUDIUS CAESAR
NERO
GALBA
OTHO
VITELLIUS
VESPASIANUS
TITUS
DOMITIANUS
NERVA (DE CAESARIBUS POST TRANQUILLUM TE TETRASTICHA)
TRAIANUS
HADRIANUS
ANTONINUS PIUS
M. ANTONINUS
COMMODUS
HELVIUS PERTINAX
DIDIUS IULIANUS
SEVERUS PERTINAX
BASSIANUS ANTONINUS SIVE CARACALLA
OPILIUS MACIUNUS
ANTONINUS HELIOGABALUS 

These are equal to Poem 5.1 to 5.100 in Alpheios

similar to issue #18

**Comment by balmas** [comment]
splitting this into 2 issues. The title is a bug in the source file.  Have submitted a PR against the Perseus repo for it https://github.com/PerseusDL/canonical-latinLit/pull/286

The issue of the subject heading display is a transform problem in our display. That's now 
#23

**Comment by balmas** [comment]
merged.
