### ISSUE TITLE
add ability to jump to a specific passage

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#214]
requested by @abrasax 

We need the ability for the user to enter the desired passage or passage range directly from the reading view so that they can get there without browsing or scrolling. The original design had this as a 'filter' option on browse passages, which we may still implement (see #81 and #80) but for now we will limit it to an input on the text display.

**Comment by balmas** [comment]
I have an initial working implementation of this in the feat-214 branch.  Will hand it over to @irina060981 to refine the ui and make it look nice :-)

Preloading all of the possible passage identifiers for a text is too performance intensive so we can't easily validate the user's input to make sure it is valid before requesting the page. But since it's easy for the user to enter an invalid input, we want at least to keep the process as responsive as possible. So I've
implemented an ajax prefetch of passage json for the requested passage identifier. If it succeeds we know the passage was valid, so we go ahead and display the new page. If it fails, we stay on the same page and they can try again or go to the table of contents.

**Comment by balmas** [comment]
I have an initial working implementation of this in the feat-214 branch.  Will hand it over to @irina060981 to refine the ui and make it look nice :-)

Here's what remains to be done:

- [ ] add a loading indicator while doing the prefetch
- [ ] make the input box look better. Maybe we should add a label to it on the desktop. on mobile not sure if there is any way to make it clearer to the user what to do without taking too much room
- [ ] add a notification if the prefetch fails (informing the user that it wasn't found and suggesting they browse the toc). Alternatively, we could bring the user directly to the browse toc page if it fails, with a corresponding message

**Comment by irina060981** [comment]
- [x] add a loading indicator while doing the prefetch
![image](https://user-images.githubusercontent.com/12377640/61455303-7ab72900-a9a6-11e9-9309-ae51439362a7.png)

added loader to the input while prefetching
for me it retrieves data very quick - so i couldn't catch it by my eyes - but it is there :)

**Comment by irina060981** [comment]
- [] make the input box look better. Maybe we should add a label to it on the desktop. on mobile not sure if there is any way to make it clearer to the user what to do without taking too much room

I could suggest only to increase the input on mobile - this way
![image](https://user-images.githubusercontent.com/12377640/61456189-ccf94980-a9a8-11e9-9efa-933c481f75da.png)

I think that using placeholder is enough - and label will be not consistent with other design.

May be it is better to add placeholder - `Jump to the passage ... ` ?

**Comment by irina060981** [comment]
- [ ] we also need to adjust the styles of the autocomplete dropdown that comes up with previous entries. it isn't readable right now

What do you mean here?
I see it this way:
![image](https://user-images.githubusercontent.com/12377640/61456573-c8816080-a9a9-11e9-833e-181deaa7a10e.png)

it seems be readable on my screen.

**Comment by balmas** [comment]
> * [x]  add a loading indicator while doing the prefetch
>   ![image](https://user-images.githubusercontent.com/12377640/61455303-7ab72900-a9a6-11e9-9309-ae51439362a7.png)
> 
> added loader to the input while prefetching
> for me it retrieves data very quick - so i couldn't catch it by my eyes - but it is there :)

that looks good to me

**Comment by balmas** [comment]
> * [ ]  make the input box look better. Maybe we should add a label to it on the desktop. on mobile not sure if there is any way to make it clearer to the user what to do without taking too much room
> 
> I could suggest only to increase the input on mobile - this way
> ![image](https://user-images.githubusercontent.com/12377640/61456189-ccf94980-a9a8-11e9-9efa-933c481f75da.png)
> 
> I think that using placeholder is enough - and label will be not consistent with other design.
> 
> May be it is better to add placeholder - `Jump to the passage ... ` ?

Ok, that's fine.  I am still struggling with the placeholder message wording. Maybe "Find passage..." ?

**Comment by balmas** [comment]
> * [ ]  we also need to adjust the styles of the autocomplete dropdown that comes up with previous entries. it isn't readable right now
> 
> What do you mean here, @balmas ?

> it seems be readable on my screen.

I was thinking about the way it looks when you have moused into them, but after looking at it again, maybe it's okay. I am not sure it's styleable anyway -- as it's just the browser behavior

![Screenshot from 2019-07-18 10-05-36](https://user-images.githubusercontent.com/644870/61464147-c84e7a00-a943-11e9-88f1-8ebaf9818f39.png)

**Comment by balmas** [comment]
> * [ ]  add a notification if the prefetch fails (informing the user that it wasn't found and suggesting they browse the toc). Alternatively, we could bring the user directly to the browse toc page if it fails, with a corresponding message
> 
> it is really a didfficult question - where to notify the user that passage search is failed.
> I see three ways:
> 
> 1. redirect to the page with a failed message and with a link to the starting (for example) passage of the book or to the browse passage for this book
> 2. add a red border and for example a red sign error to the input
> 3. add a popup with a failed message (similiar to help/bibliographic)
> 
> if to be honest - I don't know what would be the best for users - for me the 3d one is the most usual
> 
> What do you think @balmas?

Let's try 3, the popup then. thanks!

**Comment by irina060981** [comment]
>Ok, that's fine. I am still struggling with the placeholder message wording. Maybe "Find passage..." ?

I think it is good.

>I was thinking about the way it looks when you have moused into them, but after looking at it again, maybe it's okay. I am not sure it's styleable anyway -- as it's just the browser behavior

According to the following link - we could try to add some styling - may be it would work - but I think it couldn't be guaranteeв :)
https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/

**Comment by balmas** [comment]
> > Ok, that's fine. I am still struggling with the placeholder message wording. Maybe "Find passage..." ?
> 
> I think it is good.
> 
Ok, so please make that change too then, thanks!

> > I was thinking about the way it looks when you have moused into them, but after looking at it again, maybe it's okay. I am not sure it's styleable anyway -- as it's just the browser behavior
> 
> According to the following link - we could try to add some styling - may be it would work - but I think it couldn't be guaranteed :)
> https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/

Let's not worry about it.

**Comment by irina060981** [comment]
Popup would be this way:
![image](https://user-images.githubusercontent.com/12377640/61523980-c1655b80-aa58-11e9-9440-568d65c6f6de.png)

![image](https://user-images.githubusercontent.com/12377640/61524002-cc1ff080-aa58-11e9-8c27-451d54443d59.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
1) saw the loading indicator, it does exist!!!! (to repro: go from one book to an other in Ovid, metamorphoses)
2) Jump to has been changed into Find passage
3) autocomplete drop-down looks good
4) error message says: Passage not found. xx is not a valid passage reference in this text. Browse the Table of Contents for valid references.

Unfortunately, I was not able to see the autocomplete dropdown on my iphone xr. it does work on Bridget's phone
