### ISSUE TITLE
mouse over notes not working on scrolled texts

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#215]
while testing https://github.com/alpheios-project/alpheios_nemo_ui/issues/47, I come across an issue with notes not being displayed on mouse over.
go to https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi045.perseus-lat1/passage/1.31-1.35
if you use the browse passage option or the arrows on top nav to browse through pages, mouse over on notes works fine. when I use the scrolling bar to go forward in the text, the mouse over does not work anymore in the text that has been displayed by the scrolling action, it does work in the text that was already there.

**Comment by monzug** [comment]
this still does not work for passage 1.46. really super minor issue. we can postpone for after relase

**Comment by balmas** [comment]
ugh, okay so it still needs to be fixed for the final passage. I think it should be a small fix so keeping it in for now.

**Comment by balmas** [comment]
should be fully fixed now.

**Comment by monzug** [comment]
yes. all good
