### ISSUE TITLE
make sure language code references are correct

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#217]
e.g. in urn:cts:latinLit:phi0474.phi057.perseus-lat1:1.1 ἀδύνατον is tagged as lang="greek" instead of "grc" which prevents Alpheios from detecting the language properly.

reported by @monzug when testing wordlist sorting.

**Comment by balmas** [comment]
fixed all instances found in the latin texts. (only found in Cicero)

**Comment by monzug** [comment]
fixed
