### ISSUE TITLE
how to display pb miletones

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#22]
in Alpheios the reference to the book page is on a different line while in perseus is on the same line so it looks more integrated with the text
e.g. Alpheios:
<l n="423">nimirum thiasis et laeta sonantibus armis</l>
<pb n="v.2.p.376"/>

e.g. Perseus:
<lb rend="displayNum" n="281"/>Cocyti pratisque Erebi nigrantibus errant
<pb id="v.2.p.314"/>

this is from urn:cts:latinLit:stoa0089.stoa005.perseus-lat2

go in edit mode to see the tags.

**Comment by balmas** [comment]
Agree this needs to be fixed. I'm not sure if we even need or want to keep the page references or not in our display.

**Comment by balmas** [comment]
they are hidden now.  Still not sure if they are important to display.

**Comment by balmas** [comment]
will leave this as is absent user complaint.
