### ISSUE TITLE
Use CDN for embed-lib and components?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#222]
> Great changes, would help us to simplify dependency management greatly. Really appreciate it!
> I'm wondering if it's worth to use components CDN for the production version of the Nemo UI as this, in theory, would provide a more efficient loading for the users. What do you think?

I am not sure, but if it we use CDN for components I guess it would make sense to use it for embed-lib too.

I need to investigate a bit the reliability of the jsdelivr cdn before deciding but it would simplify the production deployment if I could do this so it's worth considering.

_Originally posted by @balmas in https://github.com/alpheios-project/alpheios_nemo_ui/pull/218#issuecomment-512234764_

**Comment by balmas** [comment]
don't really see any downside to this for production. for mid-release testing it's a bit of a pain because we'd have to push every build to npm, but when we have our first release candidate that would be a good time to start testing from the CDN. Will hold on to make the change then.

**Comment by balmas** [comment]
@monzug I have switched the texts-test environment over to pulling the alpheios-embedded and alpheios-components javascript and css code from the CDN rather than the local server. In theory at least, this should be a little faster for loading and caching this code. It also allows for greater separation of things -- we can release updates to the text application code and be sure the alpheios code hasn't changed. 

Because we already had released a version of embedded lib on the CDN that people might be using, I'm deploying the 3.0 code to the beta channel for now.  So you will see the following version information in the options panel:

Alpheios Embedded Library 3.0.0-beta.1.38
Alpheios Components 1.2.36

From this point on, all builds for the release of both libraries will get pushed to the CDN . I'll have to switch the embedded library over to the release channel at some point at which point the beta piece of the version info will go away. (it's necessary to make sure the release version is higher semantically than the beta version)

To test this, just verify that the code is coming from the cdn on the source tab of the developer console (see screenshot below) and that you aren't seeing any performance problems as a result.

Thanks!
![Screenshot from 2019-09-05 10-37-17](https://user-images.githubusercontent.com/644870/64352036-53a1ce80-cfc9-11e9-83b4-881e11dcd070.png)

**Comment by monzug** [comment]
Ok. Will look into it

**Comment by monzug** [comment]
see in Chrome
![cdn](https://user-images.githubusercontent.com/41396793/64359447-57881d80-cfd6-11e9-98fa-789ec9d3a8cb.JPG)

**Comment by monzug** [comment]
I didn't see any performance issue

**Comment by monzug** [comment]
tested also on safari texts env
