### ISSUE TITLE
detect non-chrome/ff/safari browsers 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#224]
we should add browser detection code which issues a notice if the user accesses the site from an unsupported browser

**Comment by balmas** [comment]
(spurred by a survey feedback report which indicated that it was not possible to select words on a Huawei mediapad. I need to update the survey to ask which browser was used but I am wondering if the default browser is an unsupported one)

**Comment by irina060981** [comment]
Created a new issue from it - https://github.com/alpheios-project/alpheios_nemo_ui/issues/243
merged and closed

**Comment by monzug** [comment]
the pop-up is there. tested on Microsoft edge
