### ISSUE TITLE
Cicero, Paradoxa stoicorum: missing UNICODE for greek characters

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#226]
I did check Scaife and it has the same issue, however Perseus doesn't.
go to Paradoxa Stoicorum, in Paradoxon I and  Paradoxon II

in Perseus: “ὅτι αὐτάρκης ἡ ἀρετὴ πρὸς εὐδαιμονίαν”
in Alpheios and Scaife:  o(/ti au)ta/rkhs h( a)reth\ pro\s eu)daimoni/an

**Comment by balmas** [comment]
fixed.

**Comment by monzug** [comment]
I can see the greek words now. thanks
