### ISSUE TITLE
set default page language for lookup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#227]
now that alpheios-project/components#509 is fixed, we should change the way the alpheios embedded lib is activated, to set the default language for the lookup according to the page that is being viewed.

**Comment by balmas** [comment]
ready for testing -- when on a greek collection page, the lookup should default to Greek and when on Latin, it should default to Latin

**Comment by monzug** [comment]
change language from latin to greek and back, also saved words on user words list, and change language in lookup. looks good to me. there is something that I need to test more carefully on saved word list, but that would be a separate issue.
