### ISSUE TITLE
hide meter milestones

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#234]
we should hide meter milestones (e.g. as in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/1?subreference=1) 

_Originally posted by @balmas in https://github.com/alpheios-project/alpheios_nemo_ui/issues/232#issuecomment-514713079_

**Comment by monzug** [comment]
there is something weird with the navigation. if I used the above link, then there is no section header, and when I use the find passage feature and says e.g. 17 and use the back arrow, it goes back one line at the time, always with no section header. However, when I use the main menu and go to the Carmina text, the section header are displayed. when I use the find passage feature with single or double digit, it does as above: show the text with no section header. when I enter e.g. 4.10 then the section header are displayed. however also in this scenario the back arrow, will go back one line at the time

**Comment by balmas** [comment]
> there is something weird with the navigation. if I used the above link, then there is no section header, and when I use the find passage feature and says e.g. 17 and use the back arrow, it goes back one line at the time, always with no section header. However, when I use the main menu and go to the Carmina text, the section header are displayed. when I use the find passage feature with single or double digit, it does as above: show the text with no section header. when I enter e.g. 4.10 then the section header are displayed. however also in this scenario the back arrow, will go back one line at the time

yes, this the same problem as reported in #232 and #193. It's not an easy fix.

**Comment by monzug** [comment]
can I close this one in favor of the other two?

**Comment by balmas** [comment]
Yes, let's close.
