### ISSUE TITLE
Advanced notice for unsupported browsers

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios_nemo_ui#243]
> > However, one way we could mitigate this -- since this is just for the alpheios nemo application, which has the ability to store browser cookies, we could do a more advanced notice, which allowed the user to ignore the warning and not get it again -- similar to the way the gdpr consent notice works . What do you think @irina060981 and @kirlat ?
> 
> I think that it should be organized similiar - we should add a banner with the message and with the following buttons: Got it and Not show again (may be some different text).
> And add a specific handler to Not show again.
> But it should somehow differs frim the cookies bar :)
> 
> @balmas - should I close this PR and change the workflow to this? Or should I merge this variant and create a new issue?

let's merge this variant and then create a new issue for the refinement. Thanks!

_Originally posted by @balmas in https://github.com/alpheios-project/alpheios_nemo_ui/pull/240#issuecomment-516182812_

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
warning message show now appear as a banner near the top of the screen, that user can hide and not see again (for 10 days)

**Comment by monzug** [comment]
on desktop, I saw the banner. still trying to repro on IE on mobile

![desktop-ie2](https://user-images.githubusercontent.com/41396793/62719823-c9b91280-b9d6-11e9-812a-e5a86c033acb.JPG)

**Comment by monzug** [comment]
banner did not show in IE on my Samsung and on my iphone XR

**Comment by balmas** [comment]
it should be there on mobile. back to @irina060981 to investigate.

**Comment by irina060981** [comment]
There is no bug here - I have checked it in IE on Samsung and Iphone.

The check for unsupported browser works as following:
1. Alpheios embed activates on page load and starts to work
2. If there is an error (if browser is unsupported than the code throws Syntax error), then `window.onerror` handler works. And It first checks Inside this handler if this browser is in the unsupported list.
3. If it is in unsupported list than it shows the banner about unsupported browser.

But it works well in IE on Samsung and Iphone, that's why there is no `window.onerror`, that is why there is no banner here.

**Comment by monzug** [comment]
irina060981, Thanks for walking through the mobile functionality and the banner showed up as you suggested. see screenshot

![IMG_3849](https://user-images.githubusercontent.com/41396793/62779833-3fc68380-ba82-11e9-967d-351c256f44fb.PNG)

two questions here: 
1) there is inconsistency between IE on mobile and IE on desktop where the banner is generated immediately (unless I got an error immediately on landing page)
2) Advanced notice implies a quick way to communicate info.
to wait for an error in IE before generating the banner can take some times, like few lookups or double-clicks.

**Comment by balmas** [comment]
ah, you know in the code review I missed the fact we were only showing the banner when an error was thrown.

@irina060981 I think I would like always to show the banner if we know we are using an unsupported browser.  It's possible some functionality will fail without errors being thrown, so I'd rather just warn the user upfront, as @monzug suggests.  Could we do it on document loaded?

**Comment by irina060981** [comment]
> @irina060981 I think I would like always to show the banner if we know we are using an unsupported browser. It's possible some functionality will fail without errors being thrown, so I'd rather just warn the user upfront, as @monzug suggests. Could we do it on document loaded?

We could do this way, but if we are going to show the banner only by the name (may be with version ? ) and not checking its work ability, than we should have some exact list, I believe.
What then would be the list?
Simply Chrome, Firefox, Safari? What versions?

There are two ways to work with lack of functionality:
   - catch the fact that it is not working (by catching the error or checking the existance of some objects/method) - this is commonly used
   - propose that this won't work by some things - in our case by knowing the name and version of the browser - it is less used approach.

According to this I chose the first approach.

I am not against to switch to the second approach, but then we would need some check:
  should I change it to check by Chrome, Firefox, Safari from the latest version (may be the latest and 5 before)?

**Comment by balmas** [comment]
Need to think about this a little bit.

**Comment by monzug** [comment]
maybe I am missing the complexity of the mobile version vs desktop. would it be possible to do as in IE on desktop?

**Comment by irina060981** [comment]
> maybe I am missing the complexity of the mobile version vs desktop. would it be possible to do as in IE on desktop?

@monzug , the problem here is not exactly in difference between desktop and mobile.
I will try to explain.

The IE on the desktop and the IE on the mobile platform are different browsers they have different inner base. That's why they work with our extension not the same way.

Desktop IE throws an error on the step when the extension registers, because we do such actions on this stage, that are not supported.
But Mobile IE looks more like Chrome and it doesn't throw an error when you try to register, it registers with a success, then it could do some action - to lookup a word, show some information. And on some step it catches an unsupported action.

And for now we show a banner when a browser catches an unsupported action, that's why it shows it quickly on the desktop and only in some time on mobile.

If we try to change the workflow, 
     first define the browser (name, version)
     decide, that it should have unsupported actions (we couldn't be sure in it in a real life)
     show the banner (and also mey be stop the activation, that could be successful)

Then we should define, what browsers should have unsupported actions.
We have thousands of different actions, so it could not be really an easy task, or we could decide to show only for the most mordern browsers.

Hope, I was able to describe my thoughts :)

**Comment by monzug** [comment]
yes, Irina you did very well. Thanks. @balmas to decide.

**Comment by balmas** [comment]
still thinking...

**Comment by balmas** [comment]
ok. Let's leave this as-is for now, pending user feedback.

**Comment by balmas** [comment]
@monzug given that decision, are we okay to mark this as verified?

**Comment by monzug** [comment]
absolutely, screenshots show that it works in IE mobile and desktop
