### ISSUE TITLE
lines in paragraphs messing up text display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#244]
if you scroll through Cicero Epistuale ad Brutum on the phone, the formatting of the page gets wonky after the first couple of sections.  

this is because the text has some embedded lines (div class=l) which are getting the flex styling used for poetry, when lines are the primary citation scheme.

**Comment by balmas** [comment]
The fix is not completely foolproof - if we have a prose text with embedded lines with line numbers we might run into problems again. But we will have to address those as they come up.

To test please double check display of both prose and poetry texts.

**Comment by monzug** [comment]
compare with Scaife and they look alike. check other texts and didn't see any issue
