### ISSUE TITLE
word selection problems on texts where words are enclosed in tags

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#252]
alpheios_nemo_ui presents some texts in which each word is wrapped in a span tag. (E.g. see Aeschylus Agamemmnon) and the word selection acts a little wonky in these cases (it's even more apparent on arabic texts see alpheios-project/alpheios_nemo_ui#55). On the desktop the entire sentence first gets selected, then it narrows to the word. On the mobile, it's very hard to select just the word.

**Comment by balmas** [comment]
this is happening because we have markup which encloses each word in a span without spaces in between them. We were using css to insert the space for the display.

We can't do much about how the browser handles selection of this markup, but we can insert the spaces into the html upon conversion from xml, rather than using css to add it.

**Comment by balmas** [comment]
qa-3.0.0.53/components 1.2.20

@monzug you can test with the following html

```
<html>
<head>
</head>
<body>
    <div lang="lat">
    <p lang="eng">
     <ol>
      <li>Clicking on "fero" should lookup "fero" not "ero"</li>
      <li>Clicking on "cu]pidinibus" should look up "cupidinibus"</li>
      <li>Clicking on "p[lacito" should lookup "p[lacito" (which oddly enough, works)</li>
     </ol>
    </p>
    <p><span data-alpheios-word-node="default"><b>f</b>ero</span> ferre tuli latus ferant</p>
        <p>sum sunt</p>
        <p>mare <span data-alpheios-word-node="default">cu[pidinibus</span> cepit differ</p>
        <p>a bene <span data-alpheios-word-node="exact">p[lacito</span></p>
        <p>ab ovo usque ad mala</p>
        <p>caeli  beatum</p>
    </div>
</body>
</html>
```

**Comment by monzug** [comment]
I compared Aeschylos, Agamemnon text end versus beta env
1) [ἀστέρας , ὅταν φθίνωσιν , ἀντολάς τε τῶν].  in the text env lookup for φθίνωσιν does work now
2) the words from line 40 to 45 are now highlighted as single word and not as sentence first.
