### ISSUE TITLE
disable feedback survey for release?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#255]
Do we want to disable the feedback survey for the release? If not, then we need to update it.

**Comment by balmas** [comment]
it should be disabled now.

**Comment by monzug** [comment]
so glad to hear that!!!!

**Comment by monzug** [comment]
Can't see any longer on mobile and desktop in text env, Alpheios Components 1.2.35.

**Comment by monzug** [comment]
tested also in Chrome and firefox on desktop
