### ISSUE TITLE
remove help button from nav bar

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#258]
dependent upon alpheios-project/components#744

Per discussion with @abrasax  it would be preferable to have just one help icon in the reading environment.   The help icon on the toolbar should open the Getting Started popup.

**Comment by balmas** [comment]
embed-lib 1.0.0.36/components 1.2.22

**Comment by monzug** [comment]
ok, that's gone but we are missing some extra info such as:

Click the Options wheel to change the default language, default dictionaries or to disable the popup (set UI Type to 'panel').

Use the arrow at the top of this panel to move it from the right to left of your browser window.

You can reopen this panel at any time by selecting 'Info' from the Alpheios Reading Tools option in your browser's context menu.

Deactivate Alpheios by clicking the toolbar icon or choosing 'Deactivate' from the Alpheios Reading Tools option in your browser's context menu.
