### ISSUE TITLE
additional getting started language updates

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#259]
[help-language.txt](https://github.com/alpheios-project/alpheios_nemo_ui/files/3486505/help-language.txt)

requested by @abrasax

**Comment by balmas** [comment]
specific change requested:

X Word Selection:

 [Tap/Double click] on a word to see lemmas, morphology, short
definitions and icons for additional resources, such as
long definitions, and, when available, inflection tables,
usage examples, and sentence diagrams.


X Word Lookup:

 Opens a lookup box in which you can enter any word to see its lemmas, morphology etc, just as if you had selected it in a text. Note that you can change the language in which the word will be searched. 

X Other Resources:

 Shows a series of icons for other resources, including
browsable inflection tables and grammars, setting options,
and, if a user has logged in, his word lists and profile.

X Main Menu:
   See available texts and access your user account.

X Table of Contents:
   Go to the table of contents of the current text.
   (top right)


And remove the Passage Navigation item

**Comment by balmas** [comment]
as with the corresponding components item, I think we should change  under Additional Resources "if a user has logged in, his..." to if you have logged in, your.." And use Additional rather than Other for consistency.

**Comment by monzug** [comment]
instead of "to see lemmas, morphology" there is retrieve
on desktop, instead of just as if you had selected it in a text, there is  just as if you had double-clicked on it in a text in web extension, but selected is used in text env both on mobile and desktop.

**Comment by balmas** [comment]
yes, need to fix that.

**Comment by monzug** [comment]
all good. one thing, in X Table of Contents:
Go to the table of contents of the current text.
(top right)   we have current work. (top right)


is it ok?

**Comment by balmas** [comment]
ah, probably 'text' is better than 'work'. Will fix. Thanks.

**Comment by balmas** [comment]
actually, I think I'm going to leave it, because we have "work" in the bibliographic help text ('Click the work's title...')
