### ISSUE TITLE
replace read icon with chevron on references (toc) display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#261]
now that we only offer the option to read and not browse on these cards, we just just use the chevron we use elsewhere to navigate to the text.

**Comment by irina060981** [comment]
Would be this way

![image](https://user-images.githubusercontent.com/12377640/62912019-cb654a80-bdc9-11e9-8c98-7d25f6ce7245.png)

![image](https://user-images.githubusercontent.com/12377640/62912038-d91ad000-bdc9-11e9-836b-914596a63a6d.png)

Merged and closed

**Comment by monzug** [comment]
tested for Ovid-Amores. question: why is Apuleios missing from my Latin authors?

**Comment by balmas** [comment]
I think Irina is just using a different set of texts in her dev environment.  It's not one of the texts we are releasing.

**Comment by balmas** [comment]
@monzug I think #267 makes this obsolete but I guess we can mark verified anyway?
