### ISSUE TITLE
alignment of find passage on desktop

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#262]
I haven't reproduced this but Harry encountered a situation where the find passage box was so far to the right the placeholder text was truncated. He normally uses a mac with relatively small screen size.  @irina060981 can you try with various resolutions?

**Comment by irina060981** [comment]
I have spent an hour to try on different resolutions, on Windows, MAC and IOS, on different texts.
I even tried to put different sizes to the parts, but I couldn't find the bug.
The only thing I have seen that on Mac on any resolution `Find passage ...` truncates to `Find passage`

**Comment by irina060981** [comment]
<img width="757" alt="Screen Shot 2019-08-13 at 14 43 01" src="https://user-images.githubusercontent.com/12377640/62915747-e55a5980-bdd8-11e9-82f8-e297ed6bb011.png">

**Comment by irina060981** [comment]
I think, when it would be possible of course, we should look at the screenshot with such bug.
May be then we could guess what layout makes it to be truncated.

**Comment by balmas** [comment]
>The only thing I have seen that on Mac on any resolution Find passage ... truncates to Find passage

Yes, that was the complaint. From the screen shot, I think it's fine and am not going to worry about it.  Thank you for investigating!

**Comment by balmas** [comment]
sorry I am going to reopen this.  The attached screenshot is what @abrasax was seeing.  Is there anything we can to to do ensure the full placeholder displays? Maybe make the input box larger?

<img width="1007" alt="Screen Shot 2019-08-09 at 9 42 07 PM" src="https://user-images.githubusercontent.com/644870/63101885-03929780-bf48-11e9-9d19-b722bdf823f6.png">

**Comment by irina060981** [comment]
I suggest to add max-width and make it larger.
But it seems to me that there are more difference here

![image](https://user-images.githubusercontent.com/12377640/63262441-4bf3e180-c2c9-11e9-9c19-180a2d1ab631.png)

the upper part is from @abrasax, the lower from my desktop
the passages navigation differes - my have it normal, the screenshot has it bold, the same for placeholder, so styles differ.
It is strange.

On my Mac it is not bold, but the input is shorter this way

**Comment by irina060981** [comment]
<img width="757" alt="Screen Shot 2019-08-13 at 14 43 01" src="https://user-images.githubusercontent.com/12377640/63262685-f3711400-c2c9-11e9-9569-d337aecd35ac.png">

**Comment by irina060981** [comment]
What is the url on the screenshot?

**Comment by balmas** [comment]
hmm. that's interesting.

**Comment by balmas** [comment]
let's just apply settings to make sure the input box is large enough to hold the entire placeholder text, if we can, and leave it at that.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
this is on mac, safari normal view
![Screen Shot 2019-08-26 at 10 03 31 AM](https://user-images.githubusercontent.com/41396793/63675398-03688680-c7e9-11e9-81a6-67ace21ac72a.png)
this is on mac, chrome - 80% zoom
![Screen Shot 2019-08-26 at 10 07 02 AM](https://user-images.githubusercontent.com/41396793/63675547-5b9f8880-c7e9-11e9-8500-3cd88893858c.png)

**Comment by monzug** [comment]
this is on chrome and FF at 80% and 100% view
![80%-chrome](https://user-images.githubusercontent.com/41396793/63675729-778a3680-c7b7-11e9-8707-21d3193fc1e3.JPG)
![80%-ff](https://user-images.githubusercontent.com/41396793/63675731-7822cd00-c7b7-11e9-9f42-c20853d1dfdd.JPG)
![100%-chrome](https://user-images.githubusercontent.com/41396793/63675732-7822cd00-c7b7-11e9-8664-89afec04a2e5.JPG)
![100%-ff](https://user-images.githubusercontent.com/41396793/63675733-78bb6380-c7b7-11e9-8326-3f97fb3ed67a.JPG)

**Comment by monzug** [comment]
Landing on page by Find passage and from TOC. looks good to me
