### ISSUE TITLE
eliminate passage level display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#267]
@abrasax would prefer that we exclude the passage dispaly, given that right now the passage level chunking is arbitrary based upon chunk size, and not on any meaningful division of the the passages.  We should keep the higher level TOC displays (e.g. book, chapter, section) but not the lowest level.  This means that texts which are only a single citation level won't get a TOC.

**Comment by balmas** [comment]
NB that as currently implemented TOC button is still there but disabled for texts which have only a single citation level (e.g. Aeschylus, some Horace, etc).  I am not sure if it looks quite right though.

**Comment by monzug** [comment]
would it be possible to hide the button completely? right now I can still see the disabled button

**Comment by balmas** [comment]
Well, that's the question. @irina060981  thought it might be better to show a disabled button than to have an inconsistent UI here. I would like @abrasax to comment on his preference when he can.

**Comment by monzug** [comment]
yes, please. we don't have any other place in alpheios with disabled buttons

**Comment by balmas** [comment]
@abrasax prefers it gone too. Will make that change.

**Comment by balmas** [comment]
@monzug suggests that we add go to first and go to last passage to the navigation options, now that we have removed the passage display.

**Comment by balmas** [comment]
I've removed the toc button rather than disabling it. For ease of testing I have also added a route to enable you to get to the last passage of a text, but no UI for it so far:

the url template is 

`https://texts-test.alpheios.net/text/<URN>/lastpassage`
e..g

https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0448.phi002.perseus-lat2/lastpassage

But this goes to the last passage of the entire text only (not last passage of book etc.)

I'm going to move further discussion of navigation to first/last passage of text/book/chapter to a new issue.

**Comment by monzug** [comment]
thanks for adding last passage! the TOC button is gone. Thanks
