### ISSUE TITLE
scroll handler for paging

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#27]
@abrasax would like us to use scrolling for pagination (default on mobile, maybe other options on desktop)

**Comment by balmas** [comment]
scroll down handler is implemented (although some improvements could be made to the display) but I guess we need a scroll up handler too in the event that you start reading in the middle

**Comment by balmas** [comment]
@monzug note that the scroll down handler is there in the test-texts environment now for both mobile and desktop -- It might be a little confusing.  I think more work is needed to more clearly show in the UI where the user is in text once they've scrolled.

**Comment by monzug** [comment]
scroll down handler on desktop: when I use the scrolling feature, and then I browse back to other sections by using the back arrow, the arrow navigation loose the forward arrow. 
see attachment
![scrolling-page](https://user-images.githubusercontent.com/41396793/54031609-3e182d00-417d-11e9-8f98-756ed52c96e1.JPG)

**Comment by monzug** [comment]
an other side effect is that mouse over a note [*] does not work after scrolling down to other section of the text. also to see the xml file is not possible as I can only access the xml of the last section.

**Comment by monzug** [comment]
confirmed that the navigation when scrolling need rework

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
scrolling on desktop: I did already mention on a separate issue (#53 ) that I can't get to last passage of a chapter and Irina is looking at it.
in the mobile, it takes sometimes for scrolling to kick in. e.g. if I am browsing De bello Gallico book (Caesar) and I select book 1, chapter 4, there is only passage 1.4.1-1.4.4. on the desktop I can scroll down to 1.15 and on. on the mobile, it takes sometimes to scroll down pass 1.4.4

**Comment by balmas** [comment]
@monzug not sure if there is more to do here or not, separate from #53?
