### ISSUE TITLE
hide embedded library notice in alpheios_nemo_ui

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#272]
@monzug reports receiving the embedded library notice in the texts environment:

![Screen Shot 2019-08-13 at 4 04 19 PM](https://user-images.githubusercontent.com/644870/63274442-cc84f480-c26d-11e9-8564-cdfa12879be8.png)

Need to review the situations under which this occurs and decide if we want to keep it or not.

**Comment by balmas** [comment]
I'm not sure it's really going to be possible to test this one, since you're looking for the negative ... i.e. you should not get the embedded library notice in the texts environment anymore. It will be there (if the circumstances are right for the touchy Safari browser) for 3rd party sites, but I'll have to set one up for you to test that. So keeping myself assigned as well.

**Comment by monzug** [comment]
well, I tried reloading and activating the icon, also switching from one site deactivate alpheios and activate again and then going to the text env. Didn't see the message. close this one for the moment. in case I see the msg I will reopen this issue.
