### ISSUE TITLE
De bello gallico: Find passage shows the Commentarius 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#279]
If I enter 4 in Find passage, it will show the COMMENTARIUS QUARTUS, which corresponds to Chapter 4 without the Chapters. in the TOC, the books are separated in chapters.  I don't mind to have the two options but it can be confusing. Is this intentional?

**Comment by monzug** [comment]
also, Amores by Ovid

**Comment by irina060981** [comment]
>maybe it would be nice if we change TOC display int this way. if I click on the book, then we display the entire book with no passages/chapter etc, if we click on the arrow next to the book, we display the book with the separation

I am not sure - I have correctly understand

![image](https://user-images.githubusercontent.com/12377640/63743063-6425bb00-c8de-11e9-99f7-c72dcd83ee79.png)

So if we click on the word Book1 - we should open the start of the first chapter of the first book, the following:
![image](https://user-images.githubusercontent.com/12377640/63743089-80c1f300-c8de-11e9-8bad-3f99e25acc51.png)


If we click on the arrow next to the book, then we should open the references:
![image](https://user-images.githubusercontent.com/12377640/63743145-a5b66600-c8de-11e9-9617-c681def1857e.png)


Am I right?

**Comment by monzug** [comment]
Irina, do the following: go to any passage of de bello gallico, then in find passage, enter 1. You’ll see the the book has no separation in chapters and the book title is Commentarius primus. Now enter 1.1 in find passage and you’ll see that the book is separated in passages. Do you see the difference with the two actions?

**Comment by monzug** [comment]
So, from TOC if i click on Book 1 I should see same as the result of find passage 1.

**Comment by irina060981** [comment]
ok, I see - thank you, @monzug :)

**Comment by irina060981** [comment]
Would be this way

Would be this way

![image](https://user-images.githubusercontent.com/12377640/63762284-e5dd0f00-c905-11e9-9135-da32b311fc87.png)

Click on the Poem1 
![image](https://user-images.githubusercontent.com/12377640/63762326-f42b2b00-c905-11e9-8699-ff936f9d7e27.png)

Click on the arrow
![image](https://user-images.githubusercontent.com/12377640/63762372-02794700-c906-11e9-953b-d76e1f79d2dd.png)


![image](https://user-images.githubusercontent.com/12377640/63762402-0dcc7280-c906-11e9-90db-1fe5a8e3560b.png)

Click on the Book1
![image](https://user-images.githubusercontent.com/12377640/63762434-1b81f800-c906-11e9-9e6f-d562460fcda3.png)

Click on the arrow
![image](https://user-images.githubusercontent.com/12377640/63762480-2e94c800-c906-11e9-9415-9cb160a0fabf.png)

Click on the chapter1 or on the arrow
![image](https://user-images.githubusercontent.com/12377640/63762516-3eaca780-c906-11e9-9bb8-a2d527039a02.png)

**Comment by monzug** [comment]
Thanks!

**Comment by irina060981** [comment]
Finally it has the following behaviour

- if click Book 1 text 
![image](https://user-images.githubusercontent.com/12377640/63815603-97b52380-c978-11e9-9ed7-ff3734c22b27.png)

- If click on Chapter 1 text
![image](https://user-images.githubusercontent.com/12377640/63815644-bf0bf080-c978-11e9-80d1-ad92b9aef7c4.png)

- If click on Chapter 1 arrow
![image](https://user-images.githubusercontent.com/12377640/63815588-879d4400-c978-11e9-88ca-646b013b6126.png)


Merged and closed

**Comment by monzug** [comment]
looks good to me. Thanks
