### ISSUE TITLE
calculating new levels doesn't work when crossing ranges

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#285]
just noticed that the separation for book 12 is placed in the wrong line. it's at line 19 but should be at line 1 which is included in book 11. see screenshot

![eneide-separator wrong](https://user-images.githubusercontent.com/41396793/63954557-4c227880-ca51-11e9-976e-f412ab8f2dd4.JPG)

**Comment by monzug** [comment]
Actually, it's not a data issue problem. it's the Go to feature. when I enter in Go to:  a passage that spans in 2 books, then the book separator goes misplaced. I think this issue has been exposed by the passages range in the Go to field.

**Comment by monzug** [comment]
this is evident in Elegiae - Propertius, Sextus  - when enter go to: 3.25-4.11

**Comment by balmas** [comment]
the problem here was that, when trying to figure out whether to insert the passage as we scroll across citation levels.  If the previous passage was a range, it was looking at the first part of the range rather than the last. (e.g if the previous range was 1.1-2.1 and the current range was 2.2-3.1, it was comparing 1.1 and 2.2 rather than 2.1 and 2.2.

**Comment by balmas** [comment]
ready for testing.

**Comment by monzug** [comment]
the separator 12 from the above scenario is gone: 
915 considunt castris ante urbem et moenia vallant.
12
Turnus ut infractos adverso Marte Latinos
defecisse videt, sua nunc promissa reposci,
se signari oculis, ultro implacabilis ardet
attollitque animos. Poenorum qualis in arvis
5 saucius ille gravi venantum vulnere pectus
it's visible when scrolling through the text or when I enter the book 12 in go to.

missing separator in Elegiae - Propertius, Sextus - when entering go to: 3.25-4.11
see screenshot
![range-elegiae](https://user-images.githubusercontent.com/41396793/64261445-8a5ce380-cefa-11e9-915e-6fb02a7d193e.JPG)

**Comment by balmas** [comment]
I can't do anything about that for this release. It's the same issue as #23 which is deferred.

**Comment by balmas** [comment]
@monzug can we verify this one and make a note in #23 ?

**Comment by monzug** [comment]
sure, post-release
