### ISSUE TITLE
group book/poem/line on line not poem

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#288]
having some issues with Find passage in Epistulae - Horace (also Ex Ponto, Ovid and Carmina, Horace). there are 2 books in TOC. the passages go from 1 to 105 and then passage start again from 5 to 70 then again from 5 to 35 and so on. if I enter 1.10 it takes to the beginning of the book so I am missing all the other passages with line 10 in book 1 and there are several line 10.
then if I enter in Go to: e.g. 2.10 (book 2, passage 10), it gives PASSAGE NOT FOUND: 2.10 is not a valid passage reference in this text. Browse the Table of Contents for valid references. when I scroll down the text in book 2 I can see that the passages # do not increase, there is only passage 2.
see also issue https://github.com/alpheios-project/alpheios_nemo_ui/issues/285

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios_nemo_ui/issues/278#issuecomment-526245694_

**Comment by balmas** [comment]
Ovid Ex Ponto and Horace Carmina were also book/poem/line

**Comment by balmas** [comment]
I think this should be less confusing now.

**Comment by monzug** [comment]
Ok, now it's much much better. Thanks. one thing that it might be confusing, even if in the go to field, the placeholder suggests to search at book level.
let's go over Amores, Ovid. it's a little confusing (I believe) that at book level I cannot search for the line but I have to add the poem and then the line.
let me explain, go to https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi001.perseus-lat2/passage/3
if you enter 3.70 in go to, is not valid but 3.1.70 is the valid entry. but you can see the line 70 right there. I guess we cannot much about it. Thinking.

**Comment by balmas** [comment]
I think the only thing we could do to help with this right now would be to add the poem headers into the text, the way I did for Catullus, so that they display.

**Comment by balmas** [comment]
@monzug what do you suggest for passage rewording?

**Comment by monzug** [comment]
agree on reworking the text rather than the message (post-release?)
in the meantime, we can add to the error message to check if chapter or poem is missing from the search field, e.g. 3.1.70

**Comment by balmas** [comment]
yes I can try that.

**Comment by balmas** [comment]
message has been updated with a hint to make sure all citation levels are present.

**Comment by monzug** [comment]
message has been updated as following:
xxxx is not a valid passage reference in this text. Are you missing a citation level (such as poem or chapter)? Browse the Table of Contents for valid references.
