### ISSUE TITLE
link to passage should not use formatted reference

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#291]
@monzug reported

receiving a server error when I click on poem ep from TOC, Amores by Ovid
https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi001.perseus-lat2/passage/1.Ep

the error is caused by the fact that we were using the human friendly formatted passage to create the link to the poem, which capitalized the subreference (i.e. the actually poem identifier is "1.ep" but we were linking to "1.Ep"

**Comment by monzug** [comment]
easy!!!! great. Thanks

**Comment by balmas** [comment]
should be fixed now.

**Comment by monzug** [comment]
yes, fixed. Thanks
