### ISSUE TITLE
google login doesn't prompt for account

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#300]
we need to make the change change here as we did in the webextension for alpheios-project/components#444, to tell auth0 to prompt the user to select their google account when they have multiple

**Comment by monzug** [comment]
@balmas, where do I find the new build? is the alpheios-release-3.0?

**Comment by monzug** [comment]
I tested in chrome and FF (also texts env) and I can see that google does offer to login with other accounts

![google-english](https://user-images.githubusercontent.com/41396793/64866755-11e8d780-d60a-11e9-8bd4-50d8600c34b3.JPG)

**Comment by monzug** [comment]
looks good to me. @balmas, is this what I am supposed to verify?

**Comment by balmas** [comment]
yep!
