### ISSUE TITLE
create signup route

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#302]
create a signup route that triggers login with the SignUp tab active.

**Comment by balmas** [comment]
if possible, we would like to also be able to distinguish if signup request is coming from Safari, and these changes in that case:

1. Hide Google login
2. Add some custom text explaining that after creating an account users have to log in using the containing app UI

**Comment by balmas** [comment]
@monzug this change to the alpheios_nemo_ui code is to add a new route, to be used only for the safari application to create an extension. so it's safe for the release, but I also had to make a couple of changes to the Auth0 universal login form which is hosted at Auth0. I believe they were very safe too, but if you could do a quick regression of the following from both the webextension and the text environment:

1. Click Login and see that you have options to both Login and SignUp

2. Click the SignUp tab on the Login form and verify  that you see the option to create an account with your Google credentials

3. Sign Up with a new address and verify that after signing up  you are automatically logged in with the new account

Thank you!

**Comment by monzug** [comment]
yes, it works as described in the above steps
