### ISSUE TITLE
update source for bootstrap?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#308]
not sure if we are using the best url for bootstrap.

We use maxcdn, but the official cdn for bootstrap is now stackpath (e.g. https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css)

Or we might want to consider just including it in our repo and referencing it locally.

Noting this because monitoring is showing some delays retrieving it from the cdn. I have a monitor running from an Australian server and it reported 11+s wait time on receiving the file from the cdn.

**Comment by balmas** [comment]
@irina060981 can you take a look into this and let me know your recommendation? Thank you!

**Comment by irina060981** [comment]
I think we should update to the latest Bootstrap version - PR is ready

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
this just needs to be verified with a general regression test of the texts-test ui

**Comment by monzug** [comment]
it works ok as I have been using the texts-test site quite a bit lately. However I am having some loading issue on a specific book (Aeschylus, Libation Bearers), other books from same author are ok. 

![Screen Shot 2020-05-22 at 4 31 26 PM](https://user-images.githubusercontent.com/41396793/82678667-48bbc680-9c4a-11ea-9ce7-2b1319817504.png)

**Comment by balmas** [comment]
> it works ok as I have been using the texts-test site quite a bit lately. However I am having some loading issue on a specific book (Aeschylus, Libation Bearers), other books from same author are ok.
> 
> ![Screen Shot 2020-05-22 at 4 31 26 PM](https://user-images.githubusercontent.com/41396793/82678667-48bbc680-9c4a-11ea-9ce7-2b1319817504.png)

ah that is more likely to be related to the treebank changes than the bootstrap stylesheets. I'll make a new issue and investigate. It could be a data issue.

**Comment by balmas** [comment]
closing this again, as the issue found is not related to the stylesheet.

**Comment by balmas** [comment]
@monzug so we can mark this one verified?
