### ISSUE TITLE
fix multi-word references

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#310]
e.g. in Ovid Met we have 

`data-alpheios_tb_ref="phi0959.phi006.alpheios-text-lat1#2-13 2-14"`

It should be 

`data-alpheios_tb_ref="phi0959.phi006.alpheios-text-lat1#2-13 phi0959.phi006.alpheios-text-lat1#2-14"`

with the doc reference repeated.

**Comment by balmas** [comment]
@monzug you should be able to test this in the texts-test environment with any word in Ovid Metamorphoses which has treebank data and which uses an enclytic (e.g. primaque, congestaque, etc)

**Comment by balmas** [comment]
test with Alpheios Components 3.3.0-qa.20200504341

**Comment by balmas** [comment]
test with Alpheios Components 3.3.0-qa.20200504341

same testing strategy as for #234

**Comment by monzug** [comment]
actually the strategy is at https://github.com/alpheios-project/alpheios-core/issues/234

see html for the following words

<span class="w alpheios-word " id="" nrefs="" tbref="2-13 2-14" data-alpheios_tb_ref="phi0959.phi006.alpheios-text-lat1#2-13 phi0959.phi006.alpheios-text-lat1#2-14">primaque</span>

<span class="w alpheios-word " id="" nrefs="" tbref="4-2 4-3 4-4 4-5 4-6" data-alpheios_tb_ref="phi0959.phi006.alpheios-text-lat1#4-2 phi0959.phi006.alpheios-text-lat1#4-3 phi0959.phi006.alpheios-text-lat1#4-4 phi0959.phi006.alpheios-text-lat1#4-5 phi0959.phi006.alpheios-text-lat1#4-6">indigestaque</span>

<span class="w alpheios-word " id="" nrefs="" tbref="4-11 4-12" data-alpheios_tb_ref="phi0959.phi006.alpheios-text-lat1#4-11 phi0959.phi006.alpheios-text-lat1#4-12">congestaque</span>
