### ISSUE TITLE
data issue in Cicero, Tusculanae Disputationes

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#316]
we should remove the / in few sentences :
e.g. (line 1.22)

E/mori nolo/,[*] sed me esse mo/rtuum nihil[*] ae/stimo.
 
and

u/nde animae excita/ntur obscura u/mbra opertae,
apertae (vel ę, -e K1)
opertę corr. V1K2
ima/gines
mo/rtuorum, alto o/stio
hostio alte (altę K1)
ostio ς alto corr. K2V1aut2 ς. locum rest. Leo. alii aut imagines mortuorum in fine relicta male Ciceroni ipsi tribuunt aut ibi mort. imagines scribunt (praeterea aperto ex ostio Mdv. opertae ex ostio Ribb. altae Klotz)
Acheru/ntis,
acheruntis (acherontis KV1 e corr.) s. s. imagines mortuorum X

and (line 1.37)
Argo/,
Enn. Med. 250
quia Argivi i/n ea
in ea add. Kc
delecti/
delecti KV2B dilecti GRV1
viri
Vecti/ petebant pe/llem inauratam a/rietis,
salso sa/nguine.
Trag. inc. 76 cf. Leo Progr. Gott. 1910 p. 21.

and

A/dsum
Trag. inc. 73
atque advenio A/cherunte
acher
Figure here!
onte K (u ss.c)
vi/x via alta atque a/rdua
Pe/r speluncas sa/xis structas a/speris pende/ntibus
Ma/xumis, ubi ri/gida constat cra/ssa
crassa s. v. add. Kc
caligo i/nferum,
ubi ...inferum Non. 272,39

**Comment by balmas** [comment]
this text has been fixed and deployed. can test at https://texts.alpheios.net

**Comment by monzug** [comment]
all fixed. see screenshot of first sentence

![Screen Shot 2021-01-13 at 3 08 30 PM](https://user-images.githubusercontent.com/41396793/104462911-6bbc3180-55b1-11eb-8368-517a70634ad1.png)
