### ISSUE TITLE
can we make the content selectable?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#32]
right now, the content in the text collections is not selectable (can't copy and paste any text) but it's in perseus and Scaife.
tested in chrome and firefox

**Comment by balmas** [comment]
ah, this was caused by some code I added to start to support swipe left/right to turn the page on a mobile device. But Harry wants to use scrolling for that anyway, so I'll remove it.

**Comment by balmas** [comment]
fixed now in the v2.0-tei-test branch

**Comment by monzug** [comment]
tested in firefox and chrome
