### ISSUE TITLE
Browse any book is not displayed correctly

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#33]
1) Click on Browse from http://texts-test.alpheios.net/collections/urn:cts:latinLit:stoa0275.stoa027/latin-classique-tertullian-ca-160-ca-230-de-spectaculis
chapters are overlapping
2) click on Browse from http://texts-test.alpheios.net/collections/urn:cts:latinLit:stoa0275.stoa001/classical-latin-tertullian-ca-160-ca-230-ad-martyras
there are only 3 numbers on the page: 1 - 6 on a row then on the next 5

**Comment by monzug** [comment]
an other example:
clcik on browse from http://texts-test.alpheios.net/collections/urn:cts:latinLit:phi0474.phi012/in-defense-of-caius-rabirius
the browse page has only numbers on it

**Comment by monzug** [comment]
Chapter 6 replaced the section number with dots and they are not working links to the section:
http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0860.phi001.perseus-lat2/references/latin-classique-curtius-rufus-quintus-historiarum-alexandri-magni-historiarum-alexandri-magni-historiarum-alexandri-magni-macedonis-libri-qui-supersunt

**Comment by balmas** [comment]
see also #30 

the current display is now bare-bones (as long as you use the navigation menus to get to it and not the links copied in this issue, which go to a still unfixed version of the display -- I'm dropping the semantic part of the link paths for now)

**Comment by balmas** [comment]
consolidating browse display issues under #42
