### ISSUE TITLE
the source pop-up stays open

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#36]
If you mouse over source, the pop-up stays open till the mouse is on source.
if you click on source, the pop-up stays open. you can double click on any word, the source pop-up stays open in the back. to close the pop-up, you need to click on source link again. is this functionality ok or do we want to add a close button?
tested in chrome and firefox. on iPhone there is only mouse over

**Comment by balmas** [comment]
I am considering removing the click handler for the popover and having it only activate on hover both on desktop and mobile. What do you think @monzug ?

**Comment by balmas** [comment]
the source popup as currently implemented is going away so I'm going to close this. Will enter a new item for implementation of the new source popup.
