### ISSUE TITLE
something not quite right the source for Petronius Arbiter, Satyricon and Seneca, Apocolocyntosis

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#37]
looking at the source of Petronius Arbiter, Satyricon, source says:
Titi Petroni Arbitri Satyricon, Petronius, with an English translation by Michael Heseltine. Seneca. Apocolocyntosis, with an English translation by W.H.D. Rouse. Petronius Arbiter, creator; Heseltine, Michael, editor and translator. London: William Heinemann Ltd. New York: G. P. Putnam's Sons. 1913.

and for Seneca, Apocolocyntosis source says:
Apocolocyntosis, Petronius, with an English translation by Michael Heseltine Seneca. Apocolocyntosis, with an English translation by W.H.D. Rouse, Seneca, Lucius Annaeus, ca. 4 B.C.-65 A.D, creator; Petronius Arbiter, creator; Rouse, W. H. D. (William Henry Denham), 1863-1950, editor; Heseltine, Michael, translator; Rouse, W. H. D. (William Henry Denham), 1863-1950, translator

looks like a combination of two books, one from Petronius and one from Seneca.

looking at Scaife:
Seneca, Lucius Annaeus (Plays), Apocolocyntosis
Apocolocyntosis, Petronius, with an English translation by Michael Heseltine Seneca. Apocolocyntosis, with an English translation by W.H.D. Rouse

and for Petronius, Satyricon
Petronius, with an English translation by Michael Heseltine. Seneca. Apocolocyntosis, with an English translation by W.H.D. Rouse. Petronius Arbiter, creator; Heseltine, Michael, editor and translator. London: William Heinemann Ltd. New York: G. P. Putnam's Sons. 1913.    (this is the same as in Alpheios)

in Perseus,
Seneca. Apocolocyntosis. W.H.D. Rouse, M.A. Litt. D. London. William Heinemann. 1913. 
and  TITI PETRONI ARBITRI SATYRICON
Petronius Arbiter. Petronius. Michael Heseltine. London. William Heinemann. 1913.

definitely both Scaife and Alpheios have some extra stuff in the editor information

**Comment by balmas** [comment]
submitted this as a PR. Won't be in a core corpus but I made the change anyway.

**Comment by balmas** [comment]
PR was merged.
