### ISSUE TITLE
implement new design for browse passages

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#42]
when I go to Browse a book like De bello gallico which has several books and chapters, it's very difficult to navigate from one section to an other. e.g. http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0448.phi001.perseus-lat2/references  (btw, why is reference in the link?)
let's say that I am reading book 2, chapter 2.4 and I want to go to book 6, chapter 3, I have to browse through the list which has one book and one chapter per line. would it be possible to group the chapters in books so visually it can be easy to select the one I am looking for without scrolling all the list?
this looks better on the iPhone where the scrolling is faster than on laptop.

**Comment by balmas** [comment]
I am really struggling with the browse display. I will ask for design assistance on this and am trying to get it to just to the point where the navigation challenges and permutations are clear enough that someone with better UI skills can come up with a suggestion. I just updated the code and hope that what's there now has reached the point where I can ask for help.

**Comment by monzug** [comment]
much much better. Thanks

**Comment by monzug** [comment]
if possible I would align all books horizontally,  maybe by adding a -> to see the next few book
so scrolling is for the chapters and going left to right for the books. just an idea.

**Comment by balmas** [comment]
the recommended design is at
Mobile:
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Browse/Book.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Browse/Chapter.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Browse/Passage.png 
and Desktop
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Browse/Book.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Browse/Chapter.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Browse/Passage.png

**Comment by balmas** [comment]
Will enter a separate issues for search/filter features in browse passages

**Comment by balmas** [comment]
ready for @irina060981 now that #117 is merged.

**Comment by balmas** [comment]
this can be tested now (except for Cicero). It's not exactly like the proposed design --- we are skipping the breadcrumb for now.

**Comment by monzug** [comment]
on mobile (1.0.0.9) - when I am in Passage (Book 1 Chapter 1),  the book 1 chapter 1 is one link.   Can book 1 be a separate link from Chapter 1? so I can click on Chapter 1 to go to Chapter and on book 1 to go to book? what do you think?

**Comment by balmas** [comment]
Hmm. I think there are a few issues here:

1. At the first level, i.e. listing of books, the header has the author name instead of the work e.g. "Book (Caesar, Julius). This should be the work name instead,e g. "Book ("De Bello Gallico")

2.I think @irina060981 linked the parent name (e.g. "Book 1 Chapter 1") because we postponed implementation of a true breadcrumb for this, but I think it is confusing because the link brings you to something different than what it says.  I think for now it would be better to just have a simple "Back" link or something similar, until we have time to fully implement the breadcrumb.  Do you agree @monzug ?

**Comment by irina060981** [comment]
1) Fixed work name
![image](https://user-images.githubusercontent.com/12377640/57426636-541c9980-7263-11e9-9399-31e8e8123021.png)

2) Changed to back - I am not sure it is the best way, but I didn't guess to anything better:
![image](https://user-images.githubusercontent.com/12377640/57426655-757d8580-7263-11e9-8855-a083906c9641.png)

**Comment by balmas** [comment]
@irina060981 what if we dropped the Book, Chapter, Passage titles, in favor of the current and then the back link? i.e. the header would then be

De Bello Gallico

Book 1 ( back link )

Book 1 Chapter 1 ( back link )

**Comment by balmas** [comment]
and maybe for the first level, i.e. book, we don't really even need the book title, because it's already in the nav?

**Comment by irina060981** [comment]
I could do this - but I think - that we need the book title for headers consistency.
Or what would be the header for the first level?

**Comment by balmas** [comment]
Ok, maybe it wasn't a good suggestion.  Alternate: keep Book, Chapter, Passage but then add back the current book, chapter, etc. but unlinked. i.e.
Book (De Bello Gallico)

Chapter (Book 1) back link 

Passage (Book 1 Chapter 1)  back link

**Comment by irina060981** [comment]
I think it would be understandable for users :)

**Comment by balmas** [comment]
ok, let's do that then!

**Comment by irina060981** [comment]
Fixed to this

![image](https://user-images.githubusercontent.com/12377640/57453517-f1022580-72a9-11e9-8c5b-ab03da6f598f.png)

![image](https://user-images.githubusercontent.com/12377640/57453538-f8293380-72a9-11e9-82c1-3bceeb3e3cd2.png)

![image](https://user-images.githubusercontent.com/12377640/57453557-feb7ab00-72a9-11e9-9052-56b3ae26e72f.png)

**Comment by irina060981** [comment]
merged and closed
