### ISSUE TITLE
Suggestion: changing book_name / Browse or book_name / Read with  Browse book_name and Read book_name

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#43]
this is just a suggestion as visually I didn't like the navigation with two words separated by a / but same link.  Would it be ok to change

Classical Latin
Caesar, Julius
Gallic War
Browse

with

Classical Latin
Caesar, Julius
Browse Gallic War       ( /  not necessary)

and

Classical Latin
Caesar, Julius
Gallic War
Read

with 

Classical Latin
Caesar, Julius
Read Gallic War ?

**Comment by balmas** [comment]
yeah I'm going back and forth on this too. I just put the links back in on the work name when reading and browsing. they currently go to a view of just that work with the browse and read links. I was thinking a better design might be to have the link on the work name switch you between browse and read. What do you think about that idea?

**Comment by monzug** [comment]
Now this has been improved with latest change in the browse feature. it's much better now because the book name is selectable when I read or browse. for Cicero, it looks good as there are 44 books.
in case of only one book for author, there are a couple of issues.
1) Virgil auhor has only book Aeneid with browse and read.
from Virgil top navigation, I go to Browse which is Virgil/Aeneid/Browse. from here, if I click on Aeneid, I go to Aeneid, aeneid browse and read with top navigation Virgil/Aeneid.
2) in case of Caesar, there is extra stuff on the book page. from Caesar, Julius, we have Gallic war with browse and read. if I click on Browse, I go to Caesar, Julius / Gallic War /  Browse. from here if I click the link Gallic War from top navigation, it goes to the Gallic war page.  here the page tithe is Gallic war with 
Gallic War, C. Iuli Caesaris Commentarii rerum in Gallia gestarum VII A. Hirti Commentarius VIII and then Read and Browse.
so, two things here: the top navigation skip the step book_name when going from author to browse or read. when I go to the book_name page, what is supposed to be the content of the page: book_name (title) and the title with the editor information? we do have those in the source already so what's the point of this extra step?

**Comment by monzug** [comment]
Hope my points are understandable... so, we skip one step going from author to read or browse. when we go to the title page from browse and read, this page does not make much sense to exist. can we kill that page/step?

**Comment by balmas** [comment]
that is what I was suggesting -- that when you click on the title from browse it would take you to read and if you click on the title from read it would take you to browse. Does that make sense?

**Comment by monzug** [comment]
absolutely. I was writing my comments when you were posting yours. YES, I
agree totally.
