### ISSUE TITLE
Browsing a book on mobile

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#46]
when browsing a book on my iPhone, I noticed that I do not have any info on the author or the text. to find out what I am browsing I need to go to any of the section or click on menu. is this ok?

**Comment by balmas** [comment]
I'm not sure what is best here. Suggestions welcome :-)

**Comment by monzug** [comment]
uhm, would it be difficult to add the source link as in Read or the title
and author as in Read?

**Comment by balmas** [comment]
Will be fixed with #74

**Comment by irina060981** [comment]
As https://github.com/alpheios-project/alpheios_nemo_ui/issues/74 is made and closed.
What else should be done here?
What additional information should be inside bibliographic popup?

**Comment by balmas** [comment]
I think this one can be closed too.

**Comment by monzug** [comment]
Bibliographic info are available in a pop-up. I have a question on the XML version:
what's the difference btw Passage and Full text? they looked the same to me! Thanks

**Comment by balmas** [comment]
> Bibliographic info are available in a pop-up. I have a question on the XML version:
> what's the difference btw Passage and Full text? they looked the same to me! Thanks

submitted this as a separate issue.

**Comment by monzug** [comment]
so it's all good.
