### ISSUE TITLE
transform betacode in Cicero, Academica 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#47]
Now that we do render notes, I realized that the abstruse text in the notes, sometimes is greek and we do not display correctly.
e.g.  text 1.30
mentem volebant rerum esse[*] iudicem
the note in the xml is 
<note>
esse ereum
<foreign xml:lang="greek">ngf</foreign>
</note>

in Perseus, the note is   esse ereum νγφ

the next note in the Alpheios  text is (hanc illi i)de/an appellabant,[*] 
<note>
appellabant
<foreign xml:lang="greek">*gw</foreign>
-labantur
<foreign xml:lang="greek">m</foreign>
<hi rend="sup">1</hi>
-lant
<foreign xml:lang="greek">pg</foreign>
</note>

 it should be      ἰδέαν   in the text   but in Alpheios is <foreign xml:lang="greek">i)de/an</foreign>
and the note from perseus is 

appellabant Γω -labantur μ1 -lant πγ

**Comment by balmas** [comment]
betacode in the notes of the Cicero texts should be transformed correctly now.

**Comment by monzug** [comment]
YES!!!!!!
