### ISSUE TITLE
Bibliographic Source has also Perseus info that I think they shouldn't be there

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#50]
Cicero, Pro S. Roscio Amerino
For Sextus Roscius of Ameria, Perseus:bib:oclc,26994431, M. Tullius Cicero. M. Tulli Ciceronis Orationes: Recognovit brevique adnotatione critica instruxit Albertus Curtis Clark Collegii Reginae Socius. Albert Curtis Clark. Oxonii. e Typographeo Clarendoniano. 1908. Scriptorum Classicorum Bibliotheca Oxoniensis.

Cicero, For Marcus Caelius
For Marcus Caelius, Perseus:bib:oclc,26994431, M. Tullius Cicero. M. Tulli Ciceronis Orationes: Recognovit brevique adnotatione critica instruxit Albertus Curtis Clark Collegii Reginae Socius. Albert Curtis Clark. Oxonii. e Typographeo Clarendoniano. 1908. Scriptorum Classicorum Bibliotheca Oxoniensis.

**Comment by balmas** [comment]
in https://github.com/alpheios-project/canonical-latinLit/commit/974ddba9a3d67cad8e023572f1850454f45d1c98.

Ready for testing at texts-test.alpheios.net. I have cleaned up all of the Cicero titles now. The bibliographic source information is a little inconsistent but I think that's less critical than the titles.

**Comment by monzug** [comment]
Epistulae Ad Atticum    should be  Epistulae ad Atticum  -  lower case 'ad' for consistency with the other titles

looks gooos. Thanks

**Comment by balmas** [comment]
fixed.

**Comment by monzug** [comment]
Thanks
