### ISSUE TITLE
Lookup does not work in the Text collections

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#51]
step to repro:
1) go to Catullus, Carmina poem 68b.31-60
http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/68b.31-68b.60
2) double click on Troia, Alpheios does not recorgnize the word (which I believe it should but this is not the point), then double click on other word, e.g. obscena
3) enter Troia in the lookup field.
4) the output will be again the obscena word
repeat with caro, obscena will show up again in the morphology panel.
Note that define and inflection do display the correct output for the lookup word.

**Comment by irina060981** [comment]
I have uploaded the last version of embeded-lib locally in alpheios_nemo_ui - this bug is not reproducable
I have tested in the current version - http://localhost:5000/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/68b.31-68b.60

It is not reproducable too.
May be this bug is solved already.

**Comment by irina060981** [comment]
But there is a difference between layouts

http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/68b.31-68b.60
![image](https://user-images.githubusercontent.com/12377640/56285009-80a82e80-6159-11e9-9e52-f5dea78f8460.png)

http://localhost:5000/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/68b.31-68b.60
![image](https://user-images.githubusercontent.com/12377640/56285024-8bfb5a00-6159-11e9-9e93-a93c9da23c82.png)

**Comment by balmas** [comment]
for some reason the texts environment didn't get updated to the latest code. I believe the display problem above is fixed now.

**Comment by balmas** [comment]
giving this to Monica to validate the original problem.

**Comment by monzug** [comment]
no longer reproducible.
