### ISSUE TITLE
Scrolling duplicates the last page

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#53]
when scrolling down from Cicero, Pro Roscio comoedo 51-undefined
(I got undefined few times but could not repro)
 http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi003.perseus-lat2/passage/51-55
going up and down scrolling causes the section 56 to be repeated several times.
conformed it does happen for other book too. see pic.
![scrolling-repetition](https://user-images.githubusercontent.com/41396793/54206519-d29ccb00-44ae-11e9-8c05-6d2e797097b8.JPG)

**Comment by monzug** [comment]
Ok. I got the undefined again
Cicero, Pro Roscio comoedo 51-undefined

it does happen by scrolling up and down and having multiple istance of section 56, at this point the 51-55 is changed into 51-undefined

**Comment by balmas** [comment]
should be fixed by the scrolling changes that were put in the test environment yesterday.

**Comment by monzug** [comment]
yes, it's fixed. However I can't scroll till the last passage. let me explain: in the first case reported in this issue, I can scroll up and down in http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi003.perseus-lat2/passage/51-55  but I can never scroll to the last passage which is http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi003.perseus-lat2/passage/56

same for the second example reported above: I can scroll up and down to
http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi037.perseus-lat1/passage/3.217-3.218 but I can't scroll to last passage: http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0474.phi037.perseus-lat1/passage/3.229-3.230

**Comment by irina060981** [comment]
Will check tomorrow

**Comment by irina060981** [comment]
will fix in the closest issue - thank you, @monzug , for such an attentive check - I haven't guess to scroll till end when testing!

**Comment by monzug** [comment]
That's what I am here for.... Thanks.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ready for testing in beta environment

**Comment by monzug** [comment]
When I scroll to the end of the book (which I do now, thanks for fixing it), the right arrow is still there but it should not be as we reach the bottom. Note that arrow is not there when using the handlers to go to last passages. see screenshot
![endofbook](https://user-images.githubusercontent.com/41396793/57537827-14ae8580-7315-11e9-96b4-91d65a3e64fe.JPG)
it's a super minor thing and we can live with it. only if it's an easy fix

**Comment by irina060981** [comment]
Yes, it is an easy fix - will do that.

**Comment by irina060981** [comment]
Merged and closed
