### ISSUE TITLE
Wordlist: internal server error when clicking on foosource 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios_nemo_ui#62]
![internal-server-error](https://user-images.githubusercontent.com/41396793/54611915-48b0ad00-4a2e-11e9-92b3-1d114a436490.JPG)

if I click on show context for the word list 'cepit ' it shows the above page. if I click on foosource, it gives me internal server error on 
http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/passage/foosource

pls disregard if this feature hasn't been implemented yet.

**Comment by balmas** [comment]
I think this is resolved now.

**Comment by monzug** [comment]
yep, gone with the wind
