### ISSUE TITLE
scrolling needs to update location

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#66]
Not sure if there is anything that can be done about this:  when I scroll the text and click on any word, the words are saved in the User word list but the link in Show Context takes you to the beginning of the section
e.g. urn:cts:latinLit:phi0893.phi003.perseus-lat2/passage/5.31-5.60    and not to    section 11.1-11.28 where the word belongs. Note that the url does not change when scrolling so it's always http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0893.phi003.perseus-lat2/passage/5.31-5.60.

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/304#issuecomment-479045330_

**Comment by irina060981** [comment]
@balmas, I tried to see, how to it works - but I failed. 
I opened
http://texts-test.alpheios.net/text/urn:cts:latinLit:phi0893.phi003.perseus-lat2/passage/5.31-5.60
scrolling is not working - so any selected word would be saved with the current link.

How could I see the scrolling and text uploading effect?

**Comment by monzug** [comment]
this is not longer reproducible in the text environment as the scrolling functionality has changed.

**Comment by balmas** [comment]
it seems scrolling is completely broken in the current environment :-( that was not intentional.

**Comment by balmas** [comment]
@irina060981 fyi, the issue that describes the desired feature is #27 . I had implemented a quick prototype of it which is apparently broken entirely now, but the functionality is still desired.

**Comment by balmas** [comment]
the prototype code is in the mobile.js file

**Comment by irina060981** [comment]
Ok, thank you @monzug and @balmas for the explanations!
@balmas , I will look at the mobile.js .
I think I saw before that behaviour (it was working someway - I remember :))
