### ISSUE TITLE
add top level nav to texts display - Desktop only

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#69]
Per the design at https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Reader/Default.png

the Desktop view of the text display should have a top level nav bar with the logo, Reading Center and Login widget which either says "Logged in as X" or presents a Login button.

The HTML template for the texts display is at https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/main/text.html

This navigation header should NOT be present on mobile.

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
yes, we do have the top nav as described above. 
when I mouse over the "logged in as x" button, there is a gray line next to the name, both in Chrome and Firefox.
My account and Open tools links have not been implemented yet. about Open tools, in the Help (or Getting started) the same icon is used for Reading Tools: View definitions, grammar, and more (in the tool panel) - question: should be Reading tools or Open tools?
Copyright info button does not work.
We have Collections and Alpheios Reader titles:  Collections, when selecting a language, an author, a work - Alpheios reader, when browsing a text. Pls confirm, if ok.
De officiis, Cicero, the # 1 chapter at the top of page is repeated twice. see screenshot
![deofficis-cicero](https://user-images.githubusercontent.com/41396793/56589963-36d5a300-65b4-11e9-9fe9-c1ab7bed32d6.JPG)

**Comment by balmas** [comment]
> My account and Open tools links have not been implemented yet. about Open tools, in the Help (or Getting started) the same icon is used for Reading Tools: View definitions, grammar, and more (in the tool panel) - question: should be Reading tools or Open tools?

see comment at https://github.com/alpheios-project/alpheios_nemo_ui/issues/72#issuecomment-486284446

**Comment by balmas** [comment]
> Copyright info button does not work.

will be done with #74

**Comment by balmas** [comment]
> We have Collections and Alpheios Reader titles: Collections, when selecting a language, an author, a work - Alpheios reader, when browsing a text. Pls confirm, if ok.

this is per the design. What do you think about it @monzug ?

**Comment by balmas** [comment]
> when I mouse over the "logged in as x" button, there is a gray line next to the name, both in Chrome and Firefox.

Giving back to @irina060981 to fix this point. The others are all either ok, or addressed in other issues.

**Comment by irina060981** [comment]
Fixed 
**normal**
![image](https://user-images.githubusercontent.com/12377640/56702303-a11e4d00-6746-11e9-8dc3-b58d029f0b21.png)

**hover**
![image](https://user-images.githubusercontent.com/12377640/56702323-b2fff000-6746-11e9-83e6-72f5dbcd8561.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
live in texts-test

**Comment by monzug** [comment]
tested in chrome and firefox, build 3.0.0.30 
Hover works only for the down arrow next to the login name.
Also the user name is not in bold as per design at https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Reader/Default.png

Pls, confirm if hover and username not in bold are ok

**Comment by irina060981** [comment]
@monzug , yes, you are right - I missed that! I have even prepared html layout for making nickname bold and not added css styles :)
and I think with hover - I should make all the text as a link, because it is not comfortable to have only a little svg as a link.
I will fix.

**Comment by irina060981** [comment]
Fixes:
![image](https://user-images.githubusercontent.com/12377640/57014805-09909100-6c55-11e9-804b-c6615a5c573d.png)

![image](https://user-images.githubusercontent.com/12377640/57014825-1c0aca80-6c55-11e9-9009-461e7faa8d9e.png)

**Comment by monzug** [comment]
Thanks for promptly fixing it

**Comment by irina060981** [comment]
Merged and closed again

**Comment by monzug** [comment]
on desktop, after I use the drop down next to logged in as x, the text is all bold (logged in as nickname) or when I hover over just Logged, it's all bold. see screenshot
![sabato-bold](https://user-images.githubusercontent.com/41396793/57319133-e852f900-70c9-11e9-812f-22802e089b8e.JPG)

**Comment by irina060981** [comment]
It is because of focus styles  - fixed

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ready for testing in beta environment

**Comment by monzug** [comment]
verified
