### ISSUE TITLE
fix the Open Tools on the Desktop texts display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#71]
See https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Reader/Default.png for how the Open Tools button is intended to display on the Desktop.

This needs to be implemented as a hook to the Alpheios embedded library's overlay nav . Final implementation is dependent upon how we approach alpheios-projects/components#341

**Comment by balmas** [comment]
I'd like to just take the Open Tools off the display for now. We can revisit this after the beta.

**Comment by irina060981** [comment]
Merged and closed

**Comment by irina060981** [comment]
@balmas , you reopened the issue, but didn't leave th explnation what I should do here :)

**Comment by balmas** [comment]
sorry :-) @abrasax would like us to increase the priority of this, and anchor the tools button in the header. But we need to make that possible first via more work on https://github.com/alpheios-project/components/issues/341 . So nothing for you to do yet ...

**Comment by irina060981** [comment]
@balmas , may be it is better to assign it to @kirlat , if he works on this issue?

**Comment by balmas** [comment]
yes, I think so. Thanks!

**Comment by balmas** [comment]
latest request from @abrasax was that we keep the floating toolbar icon on the desktop and fix it on mobile. this is ready for testing in 1.0.0.13

**Comment by monzug** [comment]
I can see the icon anchor on the header in the mobile (Samsung, iPhone). However it does not work in Language,  Authors, Works pages. it does work only in Reader view.

**Comment by balmas** [comment]
ok, will add it to the other pages too.

**Comment by balmas** [comment]
oh wait, I see, it's already there, it just doesn't work. investigating...

**Comment by balmas** [comment]
found the source. will be fixed via alpheios-project/embed-lib#56

**Comment by balmas** [comment]
should work on all displays - 1.0.0.16

**Comment by monzug** [comment]
tested on iPhone xr and Samsung 5 mini, the not longer floating toolbar works fine also in Language, Authors, Works
