### ISSUE TITLE
the help button on the texts view should produce a popup with getting started tips

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#72]
Desktop design: https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Reader/Getting-Started-Popup.png
Mobile design: https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Getting-Started.png

HTML Template: https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/main/text.html

**Comment by irina060981** [comment]
merged and closed

**Comment by monzug** [comment]
yes it does now. questions:
1) Word interaction:
Tap on a word to access the tool panel  - shouldn't be double-click?????
2) Open tools or Reading tools? I did mention this in issue #69 
3) Bibliography Information
Tap the work's title for info   -   this has not been implemented yet.
if above issues are not connected to the current issue, feel free to close this one and will enter seperate issues if needed.

**Comment by balmas** [comment]
> * Open tools or Reading tools? I did mention this in issue #69

I think this one is okay as is. The help is describing the functionality generally.  On mobile this will just be a little circle with the reading tools icon, and on Desktop it may or may not use the "Open Tools" button from the current design. Still mulling that one over, because I'm not sure we are 100% happy with the design suggestion there.

**Comment by balmas** [comment]
> 3\. Bibliography Information
>     Tap the work's title for info   -   this has not been implemented yet.

This is covered by #74
