### ISSUE TITLE
fix hover styles on texts nav bar

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#73]
Need to look at the style guide and make sure the hover styles on the texts nav bar are correct.

template file: https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/alpheios/navreader.html

**Comment by irina060981** [comment]
I have made fixes to navbars upon other PRs - is here something else should be done?
Are all hover styles are applied?

**Comment by balmas** [comment]
No, I think this is good now. Thanks!

**Comment by monzug** [comment]
is this for mobile or desktop or both? can I test in current build 3.0.0.29? 
the Back to Reader has not the same hover style as in Help and Browse.

**Comment by balmas** [comment]
mostly desktop because I don't think we really have hover on mobile.  Assigning back to @irina060981 for the consistency issue.

**Comment by irina060981** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/12377640/57059244-bf142080-6cf7-11e9-90dd-b86c914c38d3.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
this is fixed in 1.0.0.7. Thanks
