### ISSUE TITLE
implement bibliographic popup for texts display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#74]
Mobile design: https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Bibliography-Page.png

Desktop design: https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Reader/Bibliographic-Popup.png

Also need to add icon next to title to breadcrumb template
per https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Reader/Default.png and https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Default.png

template file for breadcrumb https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/alpheios/breadcrumbtext.html

**Comment by irina060981** [comment]
@balmas , I have some questions here:

![image](https://user-images.githubusercontent.com/12377640/56500077-c3e51180-654c-11e9-8176-05a8d695ea76.png)

1) is it appeared after `Browse` button clicked or some other link?
2) These links Passage, Full text - where should they lead?
3) these text is the same for all texts, different for languages or authers?
    If different - then does it store or how could be retrieved to the template?

**Comment by balmas** [comment]
@irina060981 It appears when the title/author or the little icon next to it is clicked:

![bib](https://user-images.githubusercontent.com/644870/56513384-4c899080-6500-11e9-9d90-1d0c65ccc748.png)

**Comment by balmas** [comment]
the link just download the XML ... they are already there and functional in the template. The content for this all comes from the `source_passage` macro in the text.html:

```
{% macro source_passage() %}
  <div class="alpheios-text-source d-none">
      <div class="entry-summary" lang="{{collections.current.label_lang}}">{{collections.current.label}}, <i>{{collections.current.description}}</i></div>
      <div class='Z3988' title='{{collections.current.coins}}'></div>
      <div class="copyright">Made available under the Creative Commons Attribution 4.0 International License.</div>
    <div class="xml">XML:
  	   <a href="/api/cts?request=GetPassage&urn={{objectId}}&subreference={{subreference}}" target='_blank'>Passage</a>
  	   <a href="/api/cts?request=GetPassage&urn={{objectId}}&subreference={{subreference}}" target='_blank'>Full Text</a>
    </div>
  </div>
{% endmacro %}
```

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
live in texts-test

**Comment by monzug** [comment]
all goods except for the icon next to the title that moved down a little. can we realign to the title?
see screenshot:
![move-icon-up](https://user-images.githubusercontent.com/41396793/56973476-eb367280-6b3a-11e9-95ce-aecb80ed29e9.JPG)

**Comment by irina060981** [comment]
Added fix for the icon

![image](https://user-images.githubusercontent.com/12377640/57014253-b0276280-6c52-11e9-85d2-f77dd562ed96.png)

**Comment by irina060981** [comment]
Merged and closed again

**Comment by monzug** [comment]
verified
