### ISSUE TITLE
fix display of text breadcrumb on mobile

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#75]
Per https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Default.png

Needs to be responsive, multi-line on mobile,with text title/author centered on top line, navigation centered below

**Comment by irina060981** [comment]
I have made these fixes to breadcrumb (besides the structure of breadcrumb link)
- it is responsive
- multiline on mobile
- text title/author is centered
- navigation i centered too (arrows are near the borders of the window)
Does something else should be done here?

**Comment by balmas** [comment]
that sounds good! If those changes are all already committed then we can close this and assign to Monica to verify.

**Comment by irina060981** [comment]
it looks like this now

![image](https://user-images.githubusercontent.com/12377640/56893673-d5876580-6ac6-11e9-9185-4b3a4e1fd998.png)

**Comment by monzug** [comment]
tested today and I do still see one icon for the overlay. I might have an old build.
all looks good. the new style is designed for the iPhone!!!! it looks just perfect.

I have a question for the pages in which the overlay does not pop-up such as Collections (language/authors/works). we do not have any reference to Alpheios (no logo). there might be a plan to add this info in the copyright, still I believe we should have a logo at this level. I am a big fan of the Alpheios logo...
![IMG_3417](https://user-images.githubusercontent.com/41396793/56906741-de4d4c80-6a70-11e9-8983-9c526ddd64a8.PNG)

**Comment by monzug** [comment]
I did also check the styleguide https://github.com/alpheios-project/design-guidelines/tree/master/v3/AlpheiosReader-Mobile/Collections and logo was not incorporated in the design. just checking.

**Comment by irina060981** [comment]
@monzug , may be I missed here something, but I fixed breadcumb only for texts. Not collections.
As it is shown in the issues's design (first message)

Per https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Default.png

I would check designs for collections.

**Comment by monzug** [comment]
Irina, This is a design question for Bridget. I noticed this while testing this issue. if not appropriate we can move the question out of github

**Comment by irina060981** [comment]
ok, let's wait for Bridget's answer :)

**Comment by balmas** [comment]
@monzug and @irina060981 I submitted Monica's request for the logo on the collections pages as a new issue. I agree it would be a good idea even though it's not in the design recommendation.

**Comment by monzug** [comment]
Yep, i did check the style guide and it's not there. Thanks!
