### ISSUE TITLE
add copyright/license/credit information

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#8]
we need to display copyright/licence/credit information for all the texts.

**Comment by balmas** [comment]
added in a Source popup in the v2.0-tei-test branch but we need to review the requirements for this.

**Comment by balmas** [comment]
text should now appear as 
![Screenshot from 2019-04-26 15-31-47](https://user-images.githubusercontent.com/644870/56970225-ab6c8c80-6b34-11e9-9adb-72ba5a5c6727.png)

**Comment by monzug** [comment]
tested in 3.0.0.30 - looks good. I have a question on the links to the
other sites: the only one that opens as new tab is Capitains Framework. How
about opening all as new tabs?

**Comment by balmas** [comment]
ah, yes they should. I'll fix that.
