### ISSUE TITLE
implement copyright/credits popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#82]
Design : 
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Collections/Copyright-Info-Page.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Desktop/Collections/Copryrigt-Info-Popup.png

Template: We may want to produce a new template for this but the collections template is at https://github.com/alpheios-project/alpheios_nemo_ui/blob/master/alpheios_nemo_ui/data/templates/alpheios/collection.html

Depends on #8 to actually populate this template with the data to display

**Comment by irina060981** [comment]
For https://github.com/alpheios-project/alpheios_nemo_ui/issues/82
created copyright popup (only template  - copyright-popup.html with Lorem Ipsum text)

**desktop**
![image](https://user-images.githubusercontent.com/12377640/56707386-f153da00-675b-11e9-9758-3eb7468651ed.png)

**mobile**
![image](https://user-images.githubusercontent.com/12377640/56707401-00d32300-675c-11e9-958c-8bb07796b976.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
in webextension qa-3.0.0.30 and texts-test (embed-lib 1.0.0.6)
(https://github.com/alpheios-project/webextension/tree/qa-3.0.0.30/dist and Dropbox)

**Comment by monzug** [comment]
verified
