### ISSUE TITLE
nav sections at the top should remain fixed when scrolling

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#85]
All the nav sections at the top of the page should remain fixed when scrolling.

**Comment by irina060981** [comment]
What exactly navbars should be fixed on the desktop?
both navbars - navlogin and mainnav? (it would take 105px + 80px)
or may be we should make only main nav as fixed but add there login/logout buttons to the dropdown? (it would take only 80px)

**Comment by balmas** [comment]
Yes, I think that makes sense, to have only the main nav fixed. We already have the login/logout additionally in the dropdown menu, don't we?

**Comment by irina060981** [comment]
Yes we have, but for now it is visible only on mobile.
But we could change the code to show it also for the fixed state.

**Comment by balmas** [comment]
ok, let's do that then. thanks.

**Comment by irina060981** [comment]
Fixed navbar 
![image](https://user-images.githubusercontent.com/12377640/56959494-e7cdd600-6b90-11e9-9de8-e2fe62706cd0.png)

**Comment by irina060981** [comment]
Login when navbar is fixed
![image](https://user-images.githubusercontent.com/12377640/56959804-1c8e5d00-6b92-11e9-93f4-3db4da65458b.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
this is up for testing on the texts-test site. (It's in embed-lib 1.0.0.6)

**Comment by monzug** [comment]
I reboot the mac and now it's working.... I was able to install 3.0.0.29,
yeahhhh!!!!!!

**Comment by monzug** [comment]
Nav bar is fixed in both mobile and desktop.
few things here:
1) missing logo in the Main menu on Mobile 
2) when I am logged in as nickname, the My account and Log out appear on the bottom, so what's the down arrow is supposed to do? I looked at the props here and could not find the down arrow:
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/PWA-Main-Menu-Logged-In.png  (both in desktop and mobile)

**Comment by balmas** [comment]
agree drop-down error should not be there in the menu. for the logo that will be covered with #114 I believe

**Comment by irina060981** [comment]
Yes, I missed here styles - and fixed it here
https://github.com/alpheios-project/alpheios_nemo_ui/pull/115#issuecomment-488257963

![image](https://user-images.githubusercontent.com/12377640/57051726-2f09b300-6cc6-11e9-933a-3892976128a8.png)

But I forgot to make it black - will fix

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
the arrow is not longer there on desktop and mobile. Logged in as nickname is gray now in mobile.

question:  logged in as nickname is not longer in main menu on desktop.  but I do still have a log out link.
when I am logged out, there is no option to login from main menu. Should it be there?

![login-desktop](https://user-images.githubusercontent.com/41396793/57320024-f0139d00-70cb-11e9-90a6-77897c76fe8f.JPG)

**Comment by irina060981** [comment]
@monzug , you are right! I have missed to hide logout on desktop.
Will fix it.

**Comment by irina060981** [comment]
**mobile**
![image](https://user-images.githubusercontent.com/12377640/57348281-dbe9a180-7198-11e9-9e36-55865270bafd.png)

**desktop**
![image](https://user-images.githubusercontent.com/12377640/57348296-e73ccd00-7198-11e9-8eb3-34ebd84d4a3d.png)

**fixed navbar**
![image](https://user-images.githubusercontent.com/12377640/57348318-f91e7000-7198-11e9-8b4d-b4e06368921e.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ready for testing in beta environment

**Comment by monzug** [comment]
verified as per above screenshots.
@balmas. Pls confirm that it's ok that login is not available on main menu on desktop. Thanks
