### ISSUE TITLE
review display of section breaks and line numbers

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#86]
@abrasax doesn't like design for this. Need to investigate possibilities.

**Comment by balmas** [comment]
Implemented a fix for this -- now showing section dividers only on next level.

**Comment by monzug** [comment]
while testing section and line numbers, I come across Elegiae - Propertius, Sextus
http://texts-beta.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.perseus-lat3/passage/1.1

as we do not break the text between poems (poem 1, poem 2, poem 3 etc) when scrolling down, the line numbers go from 5 to  35 and then start again at 5 which is poem 2. In perseus, it's more evident that you are going from poem 1 to poem 2.  Should we add a break between poems?

see screenshots

![elegiadi](https://user-images.githubusercontent.com/41396793/57777267-798c2600-76ef-11e9-81ba-ddf49c94737c.JPG)

**Comment by balmas** [comment]
yes, I would have expected a poem identifier to show, so the code isn't working as expected.

**Comment by balmas** [comment]
closing this, opened new issue for missing poem identifier.
