### ISSUE TITLE
flashing while loading stylesheets

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#89]
when I began introducing the new design we started getting some flashing while the styles are loaded on the page . I'm not sure what change introduced this but we have to solve. 

Also noticed by @monzug

**Comment by balmas** [comment]
from @irina060981 :  I think that it is the way css files are uploaded via flask,
first all HTML layout is loaded and only then css/jss, and css are applied after it is loaded completely.

**Comment by monzug** [comment]
haven't seen today in text-environment both in Firefox and Chrome.
