### ISSUE TITLE
different mobile/desktop text for help popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#98]
1) Word interaction:
Tap on a word to access the tool panel  - shouldn't be double-click?????

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios_nemo_ui/issues/72#issuecomment-485836352_

**Comment by balmas** [comment]
yes, we need to have it say 'double-click' on desktop and 'tap' on mobile.

**Comment by irina060981** [comment]
**>= md**
![image](https://user-images.githubusercontent.com/12377640/56702652-88af3200-6748-11e9-99a8-646901531283.png)

**xs, sm**
![image](https://user-images.githubusercontent.com/12377640/56702669-98c71180-6748-11e9-877c-55057ee5eda8.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
in texts-test (embed-lib 1.0.0.6)

**Comment by monzug** [comment]
verified in mobile and desktop.
