### ISSUE TITLE
De officiis, Cicero, the # 1 chapter at the top of page is repeated twice. 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios_nemo_ui#99]
see screenshot
![deofficis-cicero](https://user-images.githubusercontent.com/41396793/56589963-36d5a300-65b4-11e9-9fe9-c1ab7bed32d6.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios_nemo_ui/issues/69#issuecomment-485832865_

**Comment by balmas** [comment]
this should be fixed in the latest version that is live at texts-test

**Comment by monzug** [comment]
Yes. fixed in 3.0.0.30. Thanks!
